"""Controlled B.2 diagnostic: disc-velocity thrust law without induction correction.

Paper Eq. 11 states T = 2 rho A a/(1-a) u_t^2 (equivalent to 0.5 rho Ct A u_inf^2
with u_t = (1-a) u_inf). The momentum-flux audit (opus_momentum_audit) of the
published Fig. B.33 curves implies a substantially lower applied thrust. This
diagnostic tests one discrete, pre-registered alternative: T = 0.5 rho Ct A u_t^2,
i.e. OpenFOAM actuationDiskSource's 2 rho A a(1-a) U^2 evaluated with the
disc-averaged velocity. Ct=0.95 and every other input are copied unchanged from
the baseline run; nothing is fitted. This contradicts the printed Eq. 11 and is
not an author-confirmed configuration.
"""
import argparse
import json
import math
import os
from pathlib import Path
import subprocess

from common.export import digest, write
from common.provenance import snapshot_sources
from common.runs import promote
from common.storage import Storage
from common.runtime import trial_root
from .openfoam_reference import build_case, execute, rotor_source, IMAGE
from .analyze_reference import analyze
from .compare_paper_profiles import compare

THRUST_LAWS = ('eq11_induction', 'local_ct_no_induction')


def local_ct_source(config):
    """Reuse the baseline generator verbatim and swap only the thrust expression."""
    radius = config['rotor_diameter_m']/2
    eq11 = f'2.0*{math.pi*radius**2:.17g}*induction/(1.0-induction)*sqr(diskSpeed)'
    local = f'0.5*{config["ct"]:.17g}*{math.pi*radius**2:.17g}*sqr(diskSpeed)'
    text = rotor_source(config)
    if text.count(eq11) != 1:
        raise RuntimeError('Baseline thrust expression not found exactly once; refusing to patch')
    return text.replace(eq11, local)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--baseline-run', default='20261005T185748Z_2e0e1c84')
    parser.add_argument('--iterations', type=int, default=2500)
    parser.add_argument('--processes', type=int, default=4)
    parser.add_argument('--prepare-only', action='store_true')
    args = parser.parse_args()
    storage = Storage.load()
    metadata = storage.metadata('actuator_lab')
    baseline = storage.run('actuator_lab', args.baseline_run)
    config = json.loads((baseline/'configuration.json').read_text())
    model = config['turbulence_model']
    for key in ('turbulence_model', 'iterations', 'processes', 'openfoam_image', 'grid_cells_xyz',
                'actual_spacing_xyz_m', 'inlet_turbulence', 'boundary_conditions', 'time_semantics',
                'reproduction_status'):
        config.pop(key, None)  # regenerated by build_case
    previous = config.pop('diagnostic', None)
    config['diagnostic'] = {
        'baseline_run': baseline.name,
        'baseline_configuration_sha256': digest(baseline/'configuration.json'),
        'baseline_diagnostic': previous,
        'changed': 'thrust law only: 0.5 rho Ct A u_t^2 replaces paper Eq. 11 2 rho A a/(1-a) u_t^2',
        'thrust_law': 'local_ct_no_induction',
        'evidence': 'cache/actuator_lab/opus_independent/momentum_audit.json; OpenFOAM 2312 actuationDiskSourceTemplates.C line 114',
        'predicted_before_run': {'ct_applied_vs_U0': 0.62, 'basis': '1D momentum theory a=Ct/(4+Ct)'},
        'author_confirmed': False,
        'purpose': 'Test whether published curves are consistent with a disc-velocity thrust law; not parameter fitting.'}
    config['assumptions'] = list(config.get('assumptions', [])) + [
        'Thrust law deliberately differs from printed Eq. 11; hypothesis from momentum-flux audit of Fig. B.33 only.']
    target = trial_root('actuator_lab', 'opus_independent')
    build_case(target, config, model, args.iterations, args.processes)
    (target/'constant/fvOptions').write_text(local_ct_source(config))
    write(target/'thrust_law.json', {'law': 'local_ct_no_induction',
                                     'fvOptions_sha256': digest(target/'constant/fvOptions')})
    revision = snapshot_sources(storage.root, target/'source_snapshot.tar.gz')
    write(target/'provenance.json', {'code_revision': revision, 'dirty': True,
                                    'source_snapshot_sha256': digest(target/'source_snapshot.tar.gz')})
    print(target, flush=True)
    if args.prepare_only:
        return
    execute(target)
    command = ['docker', 'run', '--rm', '--network', 'none', '--cpus', '1',
               '--user', f'{os.getuid()}:{os.getgid()}', '-v', f'{target.resolve()}:/case', '-w', '/case',
               '--entrypoint', '/bin/bash', IMAGE, '-lc',
               'source /usr/lib/openfoam/openfoam2312/etc/bashrc; '
               'postProcess -fields "(U k nut)" -latestTime > log.serialProfiles 2>&1']
    subprocess.run(command, check=True)
    log = (target/'log.serialProfiles').read_text()
    if 'Cannot find functionObject' in log or 'Cannot find registered field' in log:
        raise RuntimeError('Serial profile sampling did not execute')
    summary = analyze(target)
    manifest = json.loads((target/'manifest.json').read_text())
    extras = [('thrust_law', 'thrust_law.json', 'application/json'), ('serial_profiles_log', 'log.serialProfiles', 'text/plain')]
    if summary['numerical_convergence_verified']:
        compare(target, metadata/'formal_figure_b33.json', target/'paper_comparison.json')
        extras.append(('paper_comparison', 'paper_comparison.json', 'application/json'))
    for key, name, mime in extras:
        manifest['artifacts'].append({'id': key, 'asset': name, 'sha256': digest(target/name), 'media_type': mime})
    write(target/'manifest.json', manifest)
    if summary['numerical_convergence_verified']:
        print('retained', promote(storage, target))


if __name__ == '__main__':
    main()
