from pathlib import Path
import json,hashlib
from PIL import Image,ImageDraw
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/barclays-west-photo-evidence-001';O.mkdir(exist_ok=True);C=P.parent.parent/'cache/tower_hamlets/barclays_west_photo001';C.mkdir(parents=True,exist_ok=True)
g=json.loads((R/'geometry.json').read_text());b=next(b for b in g['buildings'] if 'fcc7f76d' in b['id']);ring=b['geometry'][0]['outer'];photo=R/'references/pexels-tom-whyte-10391373.jpeg';im=Image.open(photo);im.crop((510,2550,1180,3330)).save(C/'source-crop.png')
obs={'owner_id':b['id'],'name':'Barclays eastern tower, 1 Churchill Place candidate identity','source_id':'pexels_tom_10391373','source_file':str(photo),'source_sha256':hashlib.sha256(photo.read_bytes()).hexdigest(),'source_dimensions':list(im.size),'actually_inspected':True,'crop_original_pixels':[510,2550,1180,3330],'crop_location':str(C/'source-crop.png'),'identity_basis':['Readable BARCLAYS on tall distant tower left of HSBC in full photograph','Mapped owner fcc7f76d named Barclays, reported156m, east of Crossrail/HSBC group','Other Barclays owner f9ed6834 is30m western block near ENU(-210,65); incompatible with tower silhouette/background position'],'current_status':'Progress inventory still says baseline/vector-only; standalone roof-study reference exists. Do not assume roof study is retained; inspect latest native before authoring. No existing facade study found.','visible_features':['Pale strong horizontal floor bands across dark glazing','Thin vertical mullions subdivide broad glazing runs; apparent paired lines in places','Crown has denser horizontal slats and tall thin uprights below pale coping','Narrow side face on image left; broad face carries readable sign','Lower broad facade blocked diagonally by foreground Crossrail/low office; no entrance evidence'],'mapped_edge_proposal':{'interpretation':'Broad face provisionally west-facing from west/northwest Crossrail viewpoint; narrow left face provisionally north. Building identity stronger than exact edge registration.','west_chain_indices_zero_based':[21,22,23,24,0],'edges':[[ring[i],ring[(i+1)%len(ring)]] for i in [21,22,23,24,0]],'not_yet_calibrated':True},'supported_next_components':['Bounded upper west glazing backing with real shallow pale horizontal bands','Thin vertical members only in a photo-registered subset','Separate denser crown louvre zone only after native roof/body interface inspection'],'not_supported':['Full perimeter window arrays','Precise floor or bay count from this crop alone','Entrance and lower occluded frontage','Logo as geometry or photo texture','Crown equipment or altered roof','Assigning foreground low office panels to this owner'],'uncertainty':['No calibrated Tom camera; no landmark reprojection residual yet','Mapped west edge has small offsets; photo insufficient to flatten into single continuous wall','Absolute heights, setbacks, depths and spacing unresolved','Capture date unknown; current body/roof reference may differ temporally'],'decision':'Evidence-to-component proposal only. Sufficient tower identity and qualitative hierarchy; insufficient exact edge/height registration for honest geometry now. Preserve original body and roof in any subsequent additive study.'}
(O/'evidence.json').write_text(json.dumps(obs,indent=2));(O/'proposal.md').write_text('''# Barclays upper-west facade evidence proposal

Exact owner: overture-building-fcc7f76d-8a32-4c4b-93cf-528a3bdf79e3. Actual full Tom Whyte photo and original-resolution crop inspected. Readable BARCLAYS tower sign, height and background position discriminate this eastern tower from similarly named western low owner f9ed6834. No new acquisition.

The crop resolves pronounced pale horizontal bands across dark glazing, fine vertical members and a denser crown slat zone. Lower facade is diagonally obscured by foreground buildings/Crossrail. Broad face provisionally corresponds to mapped west chain edges21–24 and0; this has not been camera calibrated and must not be treated as exact correspondence.

Recommend next bounded step: register roof corners/HSBC/Crossrail landmarks and inspect latest native owner in isolation, then author only an upper west subset with shallow bands/recessed glazing and thin members. Do not extrapolate count, flatten mapped offsets, add lower entry, transfer foreground facade, or alter roof. No geometry authored at this gate because absolute height/edge mapping remains unresolved. Photo crop stays cache-only, not in package. Existing progress entry is baseline; separate roof references do not establish retained status.
''')
canvas=Image.new('RGB',(1000,700),'white');d=ImageDraw.Draw(canvas)
def xy(p):return ((p[0]+330)*1.25+20,650-(p[1]+100)*2)
for q in g['buildings']:
 if q.get('name') not in ['Barclays','HSBC UK','Crossrail Place']:continue
 pts=q['geometry'][0]['outer'];d.polygon([xy(p) for p in pts],fill='#d9e3e8',outline='#54606b');cx=sum(p[0] for p in pts)/len(pts);cy=sum(p[1] for p in pts)/len(pts);d.text(xy((cx,cy)),q['name']+' '+q['id'].split('-')[2][:8],fill='black')
for i in [21,22,23,24,0]:d.line([xy(ring[i]),xy(ring[(i+1)%len(ring)])],fill='red',width=5)
d.text((20,15),'Mapped plan: red = provisional west face chain, NOT calibrated photo projection',fill='black');d.text((20,35),'North upward; similarly named western low block is a distinct owner',fill='black');canvas.save(O/'owner-discrimination.png')
(O/'hashes.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.iterdir() if p.name!='hashes.json'},indent=2))
