from pathlib import Path
import bpy,bmesh,json,hashlib
from mathutils import Vector
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/one_canada_detail_gap003';O.mkdir(exist_ok=True);src=P/'runs/canary_wharf_appearance_quay1_recess_001/region.blend';name='Canada_317cf479fcef_steel';ID='overture-part-0c84e402-a7c0-399a-a2af-317cf479fcef';bpy.ops.wm.read_factory_settings(use_empty=True)
with bpy.data.libraries.load(str(src),link=False) as (a,b):b.objects=[name]
base=b.objects[0];bpy.context.collection.objects.link(base)
def sig(o):return hashlib.sha256(json.dumps({'v':[list(v.co) for v in o.data.vertices],'f':[list(p.vertices) for p in o.data.polygons],'mi':[p.material_index for p in o.data.polygons],'materials':[m.name for m in o.data.materials],'props':dict(o.items())},sort_keys=True,default=list).encode()).hexdigest()
original=sig(base);g=json.loads((R/'geometry.json').read_text());f=next(q for q in g['buildings'] if q['id']==ID);ring=f['geometry'][0]['outer'];a,b=map(Vector,ring[:2]);t=(b-a).normalized();n=Vector((t.y,-t.x));# check signed ring normal: area positive =>outwardright
assert n.x<-.9
L=(b-a).length;verts=[];faces=[];posts=[]
for j in range(30):
 center=L*j/29;lo=max(0,center-.05);hi=min(L,center+.05);p=a+t*lo;q=a+t*hi;v=[(xy.x+n.x*d,xy.y+n.y*d,z) for z in [210.005,211.365] for xy,d in [(p,-.08),(q,-.08),(q,.115),(p,.115)]];off=len(verts);verts+=v;faces += [tuple(off+i for i in face) for face in [(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)]];posts.append({'index':j,'along_m':[lo,hi],'depth_m':[-.08,.115],'z':[210.005,211.365]})
s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.samples=40;s.render.resolution_x=1300;s.render.resolution_y=900;s.render.resolution_percentage=100;s.world=bpy.data.worlds.new('Crown inspection world');s.world.use_nodes=True;s.world.node_tree.nodes['Background'].inputs['Color'].default_value=(.66,.72,.79,1);s.world.node_tree.nodes['Background'].inputs['Strength'].default_value=.8;bpy.ops.object.light_add(type='SUN');bpy.context.object.data.energy=2;bpy.context.object.rotation_euler=(.3,-.6,-.5);bpy.ops.object.camera_add();cam=bpy.context.object;s.camera=cam;cam.data.type='ORTHO';mid=(a+b)/2
views=[('whole',Vector((-47,-41,222)),Vector((-70,35,24)),57),('close',Vector((mid.x,mid.y,211)),Vector((-13,6,3)),9)]
def render(prefix):
 for key,c,offset,scale in views:
  cam.location=c+offset;cam.rotation_euler=(c-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.ortho_scale=scale;s.render.filepath=str(O/(prefix+'-'+key+'.png'));bpy.ops.render.render(write_still=True)
render('before');me=bpy.data.meshes.new('Roof screen west uprights estimated');me.from_pydata(verts,[],faces);me.update();bm=bmesh.new();bm.from_mesh(me);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));assert all(e.is_manifold for e in bm.edges);assert all(f.calc_area()>1e-10 for f in bm.faces);bm.to_mesh(me);bm.free();ob=bpy.data.objects.new('Canada_roofscreen_west_uprights_estimated003',me);bpy.context.collection.objects.link(ob);me.materials.append(base.data.materials[0]);ob['building_id']=ID;ob['source_owner_ids']=[ID];ob['research_object_id']='one_canada_detail_gap003::west_screen_uprights';ob['coverage']='Onlywestedge0roofscreenverticalposts; qualitativeAnna westview +Altafassembly, count/pitch/depthestimated';ob['geometry_basis']='Addedonly30closedposts connectingretained5horizontalrings, noheight/roofchange';assert sig(base)==original;render('after');bpy.ops.wm.save_as_mainfile(filepath=str(O/'canada-crown.blend'),compress=False);bpy.ops.object.select_all(action='DESELECT');base.select_set(True);ob.select_set(True);bpy.ops.export_scene.gltf(filepath=str(O/'canada-crown.glb'),export_format='GLB',use_selection=True,export_extras=True,export_draco_mesh_compression_enable=False)
expected={}
for o in [base,ob]:o.data.calc_loop_triangles();expected[o.name]={'triangles':len(o.data.loop_triangles),'materials':sorted(set(o.data.materials[p.material_index].name for p in o.data.polygons)),'building_id':o.get('building_id')}
bpy.ops.wm.open_mainfile(filepath=str(O/'canada-crown.blend'));assert sig(bpy.data.objects[name])==original;bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'canada-crown.glb'));actual={o.name:{'triangles':len(o.data.polygons),'materials':sorted(set(o.data.materials[p.material_index].name for p in o.data.polygons)),'building_id':o.get('building_id')} for o in bpy.data.objects if o.type=='MESH'};assert actual==expected
(O/'checks.json').write_text(json.dumps({'owner_id':ID,'source_blend':str(src),'source_sha256':hashlib.file_digest(src.open('rb'),'sha256').hexdigest(),'original_mesh':name,'original_signature':original,'original_unchanged':True,'native_reopened':True,'independent_glb_verified':True,'inventory':actual,'posts':posts,'edge':{'index':0,'a':list(a),'b':list(b),'outward_normal':list(n)},'source_photos':['pexels_anna_19572396','pexels_altaf_19330277'],'limits':['Westface supportedby independentAnna contextualview, Altafcardinalface itselfambiguous.','30posts29bays dimensions/cadenceestimated; notexactphotogrammetriccount.','Retainedfivehorizontalrings andpyramidexact, farfacesnotdecorated.']},indent=2));print('DONE',actual)
