"""Bounded massing hypothesis, exact Westferry House owner footprint; no facade claims."""
from pathlib import Path
import bpy,json,hashlib
from mathutils import Vector
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';source=R/'references/westferry_house_roof_study.json';r=json.loads(source.read_text());out=R/'exports/westferry-house-massing-001';out.mkdir(exist_ok=False)
bpy.ops.wm.read_factory_settings(use_empty=True)
mesh=bpy.data.meshes.new('Westferry House observed-plateau massing');mesh.from_pydata(r['vertices'],[],r['faces']);mesh.update();ob=bpy.data.objects.new('WestferryHouse_plateau_massing_hypothesis',mesh);bpy.context.collection.objects.link(ob);ob['building_id']=r['building_id'];ob['research_object_id']='westferry-house-massing::'+ob.name;ob['source_owner_ids']=[r['building_id']];ob['coverage']='EA DSM-supported two-level massing hypothesis; facades and ground interface unresolved';ob['vertical_datum']='Scene Z = EA ODN -4.28000021m; basez0 unresolved ground';ob['source_ids']='overture_buildings_20260923,ea_lidar_dsm_1m'
for name,col in [('Illustrative pale massing not material evidence',(.64,.60,.50,1)),('Illustrative roof not material evidence',(.18,.26,.29,1))]:
 m=bpy.data.materials.new(name);m.diffuse_color=col;m.use_nodes=True;m.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value=col;m.node_tree.nodes['Principled BSDF'].inputs['Roughness'].default_value=.8;mesh.materials.append(m)
for p,i in zip(mesh.polygons,r['materials']):p.material_index=i
s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.samples=24;s.render.resolution_x=1200;s.render.resolution_y=900;s.render.resolution_percentage=100;s.world=bpy.data.worlds.new('Inspection world');s.world.use_nodes=True;s.world.node_tree.nodes['Background'].inputs['Color'].default_value=(.6,.68,.75,1);s.world.node_tree.nodes['Background'].inputs['Strength'].default_value=.8
bpy.ops.object.light_add(type='SUN');sun=bpy.context.object;sun.name='Temporary inspection sun';sun.data.energy=2;sun.rotation_euler=(.5,-.4,-.7)
bpy.ops.object.camera_add();cam=bpy.context.object;s.camera=cam;cam.data.type='ORTHO';cam.data.ortho_scale=92;target=Vector((-462,67,26));cam.location=target+Vector((-100,-150,90));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler()
bpy.ops.wm.save_as_mainfile(filepath=str(out/'westferry-house.blend'),compress=False);bpy.ops.object.select_all(action='DESELECT');ob.select_set(True);bpy.context.view_layer.objects.active=ob
bpy.ops.export_scene.gltf(filepath=str(out/'westferry-house.glb'),export_format='GLB',use_selection=True,export_extras=True,export_draco_mesh_compression_enable=False)
for label,offset in [('front',(-100,-150,90)),('roof',(-5,-10,180)),('rear',(90,130,75))]:
 cam.location=target+Vector(offset);cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(out/(label+'.png'));bpy.ops.render.render(write_still=True)
expected=len(r['faces']);expected_bounds=[[min(v[i] for v in r['vertices']) for i in range(3)],[max(v[i] for v in r['vertices']) for i in range(3)]]
bpy.ops.wm.open_mainfile(filepath=str(out/'westferry-house.blend'));objects=[o for o in bpy.data.objects if o.type=='MESH'];assert len(objects)==1 and len(objects[0].data.polygons)==expected and objects[0]['building_id']==r['building_id']
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(out/'westferry-house.glb'));objects=[o for o in bpy.context.scene.objects if o.type=='MESH'];points=[o.matrix_world@v.co for o in objects for v in o.data.vertices];bounds=[[min(v[i] for v in points) for i in range(3)],[max(v[i] for v in points) for i in range(3)]];triangles=sum(len(o.data.polygons) for o in objects);assert triangles==expected;assert all(o.get('building_id')==r['building_id'] for o in objects);assert all(abs(a-b)<.0001 for ar,br in zip(bounds,expected_bounds) for a,b in zip(ar,br));assert all(len(o.data.materials)>0 for o in objects)
report={'native_reopened':True,'independent_glb_import':True,'triangles':triangles,'bounds_enu_m':bounds,'owner_ids':[r['building_id']],'source_json_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'native_sha256':hashlib.sha256((out/'westferry-house.blend').read_bytes()).hexdigest(),'glb_sha256':hashlib.sha256((out/'westferry-house.glb').read_bytes()).hexdigest(),'visual_reviewed':False,'scope':'Isolated exact-footprint two-level massing study, unverified photo-owner facade seam, no facade or raised-ground reconstruction','numerical_source_checks':r['checks'],'support':r['support'],'replacement_interface':r['interfaces']};(out/'verification.json').write_text(json.dumps(report,indent=2)+'\n')
