import bpy,bmesh,json,math,hashlib
from pathlib import Path
from mathutils import Vector
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';E=R/'exports/impounding-evidence-001';O=R/'exports/impounding-roof-study-001';O.mkdir(exist_ok=True);d=json.loads((E/'audit.json').read_text());a=d['fit_parameters_ridge_odn_across_position_slopes_along_grade'];v=[Vector(q) for q in d['source_geometry']['geometry'][0]['outer']];eu=(v[1]-v[0]).normalized();ev=(v[3]-v[0]).normalized();r0=v[0]+(v[1]-v[0])*(a[1]/(v[1]-v[0]).dot(eu));r1=v[3]+(v[2]-v[3])*((a[1]-(v[3]-v[0]).dot(eu))/(v[2]-v[3]).dot(eu));xy=[v[0],r0,v[1],v[2],r1,v[3]]
def z(q):
 u=(q-v[0]).dot(eu);t=(q-v[0]).dot(ev);return a[0]-(a[2] if u<a[1] else a[3])*abs(u-a[1])+a[4]*(t-14)-4.28000021
verts=[(*q,z(q)) for q in xy]+[(*q,z(q)-.15) for q in xy];faces=[(0,1,4,5),(1,2,3,4),(11,10,7,6),(10,9,8,7)]+[(i,(i+1)%6,(i+1)%6+6,i+6) for i in range(6)]
bpy.ops.wm.read_factory_settings(use_empty=True);me=bpy.data.meshes.new('Mapped gable roof skin');me.from_pydata(verts,[],faces);me.update();bm=bmesh.new();bm.from_mesh(me);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));assert all(e.is_manifold for e in bm.edges);assert all(f.calc_area()>1e-8 for f in bm.faces);bm.to_mesh(me);bm.free();ob=bpy.data.objects.new('Impounding roof only - unresolved epoch',me);bpy.context.collection.objects.link(ob);ob['building_id']=d['source_geometry']['id'];ob['source_owner_ids']=[ob['building_id']];ob['scope']='Roof-only DSM gable hypothesis; 0.15m illustrative thickness; northwest low-return patch interpolated uncertain; not current whole-building replacement';ob['datum']='ODN minus 4.28000021m';m=bpy.data.materials.new('Neutral unverified roof material');m.diffuse_color=(.24,.27,.28,1);me.materials.append(m)
s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.samples=24;s.render.resolution_x=1000;s.render.resolution_y=800;s.render.resolution_percentage=100;s.world=bpy.data.worlds.new('QA studio');s.world.use_nodes=True;s.world.node_tree.nodes['Background'].inputs['Strength'].default_value=.8
ld=bpy.data.lights.new('QA Sun','SUN');ld.energy=2;lo=bpy.data.objects.new('QA Sun',ld);s.collection.objects.link(lo);lo.rotation_euler=(.3,-.6,-.4);cam=bpy.data.objects.new('QA Camera',bpy.data.cameras.new('QA Camera'));s.collection.objects.link(cam);s.camera=cam;cam.data.type='ORTHO';cam.data.ortho_scale=42;C=sum((Vector(t) for t in verts),Vector())/len(verts)
for name,offset in [('overview',(-35,40,30)),('roof',(0,0,60)),('rear',(30,-40,22))]:
 cam.location=C+Vector(offset);cam.rotation_euler=(C-cam.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(O/(name+'.png'))
 if name=='overview':
  bpy.ops.wm.save_as_mainfile(filepath=str(O/'impounding-roof.blend'),compress=False);bpy.ops.object.select_all(action='DESELECT');ob.select_set(True);bpy.ops.export_scene.gltf(filepath=str(O/'impounding-roof.glb'),export_format='GLB',use_selection=True,export_extras=True,export_draco_mesh_compression_enable=False)
 bpy.ops.render.render(write_still=True)
expected=[[min(q[i] for q in verts) for i in range(3)],[max(q[i] for q in verts) for i in range(3)]];bpy.ops.wm.open_mainfile(filepath=str(O/'impounding-roof.blend'));assert any(o.type=='MESH' and o.get('building_id')==d['source_geometry']['id'] for o in bpy.data.objects)
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'impounding-roof.glb'));ms=[o for o in bpy.data.objects if o.type=='MESH'];assert len(ms)==1;ob=ms[0];assert ob.get('building_id')==d['source_geometry']['id'];vv=[ob.matrix_world@v.co for v in ob.data.vertices];actual=[[min(q[i] for q in vv) for i in range(3)],[max(q[i] for q in vv) for i in range(3)]];error=max(abs(actual[j][i]-expected[j][i]) for j in range(2) for i in range(3));assert error<.0001
rep={'native_reopened':True,'glb_reimported':True,'owner_id':ob['building_id'],'mesh_count':len(ms),'triangles':len(ob.data.polygons),'bounds_enu':actual,'roundtrip_max_error_m':error,'material_names':[m.name for m in ob.data.materials],'pre_export_closed_manifold':True,'zero_area_faces':0,'illustrative_thickness_m':.15,'whole_building_replacement':False,'visual_reviewed':False};(O/'checks.json').write_text(json.dumps(rep,indent=2));print(rep)
