from pathlib import Path
import json,hashlib,zipfile
S=Path(__file__).resolve().parent;R=S/'input/canary_wharf_20261007';O=R/'exports/constant-massing-001'
p=R/'references/constant_diagnostic.json';j=json.loads(p.read_text());j['decision']='Independent estimated flat-elevation candidate subsequently authored; full-domain RMSE/P95 deterioration retained. No regional integration.';p.write_text(json.dumps(j,indent=2))
report={'owner':'overture-building-7ddba86f-e5b2-4bde-bdd4-9b0e723628cc','name':'Constant House','status':'Independent candidate; recommend hold fullfootprint application pending lowedge/extension interpretation','actual_views_reviewed':['overview.png','context-review.png','full_domain_evaluation.png','constant_diagnostic.png','constant_profiles.png'],'source_height':'12.52923489m from Microsoft ML Buildings, not a direct height measurement','roof':'20.05223804m ODN; common offset4.28000021 gives15.77223783m scene','all_valid_cells':617,'missing_projections':0,'mesh_count':1,'triangles':28,'full_domain_rmse_old_new':[5.51201080,6.61186787],'full_domain_p95_old_new':[14.16763492,17.41063781],'full_domain_median_abs_old_new':[3.27576590,.61423636],'native_glb_verified':True,'neighbor_contacts':0,'neighbor_nearest_sample_m':12.75042248,'limitations':['Coherent north-edge lowstrip, northeast lowpatch and southeast extension are covered by an uncertain single envelope.','Interiorplane stable but full-domainRMSE/P95 worsen; no overall accuracy claim.','DTM insideowner1.846–2.719ODN is belowcommon4.28datum; flatbase0 is illustrative, groundcontact unreviewed.','Actual rasterflightdateunknown. No photos verifyfacades or roofedgeextent.','No invented pitch, terrace, holes or equipment.']}
(O/'report.json').write_text(json.dumps(report,indent=2));(O/'report.md').write_text('''# Constant House: independent flat-roof elevation candidate

The spatially stable main roof is approximately20.052 m ODN, corresponding to15.772 m scene elevation using the unchanged4.28000021 m offset. Its previous12.529 m extrusion comes from Microsoft ML Buildings, not direct measurement. A robust constant plane was fit to all3 m geometric-inset cells, without elevation filtering; six spatial holdouts estimate20.014–20.068 m ODN. No pitch or secondary terrace was invented.

The full mapped footprint remains preserved, including the uncertain southeast extension. Actual frozenmesh evaluation includes all617 valid owner DSM cellcentres: zero missing projections, RMSE5.5120→6.6119 m and P9514.1676→17.4106 m worsen, while median absolute error3.2758→0.6142 m improves. Coherent low north-edge strip, northeast patch and southeast extension remain unresolved. Only14 wholefootprintcells matchDTM within0.1m, so lowvalues cannot all be labeledground. The innerplane evidence does not establish that its height applies to every boundary cell or extension.

This is a useful explicit geometry hypothesis, not a validated wholebuilding correction. Recommend holding fullfootprint application pending roofedge/extension evidence; do not hide the full-domain deterioration by reporting only inset performance. Original geometry is unchanged outside this independent asset.

One closed mesh,28 triangles. Native reopen and independent GLB geometry/ID/material/bounds checks pass. Neighbor BVH returns0contacts; nearest sampled vertex12.7504 m. Overview, neighborcontext, DSM/DTM and full-domain residual images were actually inspected. The L-shaped envelope is coherent but all facades remain plain and unverified. Flatbase0 is illustrative; localDTM is below the commondatum and groundcontact needs separate review.

Sources: existing EA1m DSM/DTM under OGLv3 (Contains Environment Agency information © Environment Agency copyright and/or database right2022), actual capture dateunknown. Overture2026-09-23.1 footprint derives from OSMw789802744@3, update2025-05-10; height property derives from Microsoft ML Buildings, ODbL. No new imagery acquired. sources.zip contains scripts/reports, not rawrasters/photos. No globalprogress or regionalassembly changes.
''')
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in list(S.glob('constant_*.py'))+list((R/'references').glob('constant*.json'))+list(O.glob('*.json'))+[O/'report.md']:z.write(p,str(p.relative_to(S)))
print(hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest())
