(async()=>{
const fs=require('fs'),path=require('path'),crypto=require('crypto');const {default:p}=await import(path.resolve('cache/framework/browser-tools/node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js'));
const out=process.env.UWM_BROWSER_OUTPUT||'cache/tower_hamlets/browser_speckle_diagnosis';fs.mkdirSync(out,{recursive:true});const browser=await p.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const report={errors:[],experiments:[]};
try{const page=await browser.newPage();await page.setViewport({width:1440,height:1000});page.on('pageerror',e=>report.errors.push(e.message));await page.setRequestInterception(true);page.on('request',r=>{if(r.url().endsWith('/viewer/main.mjs')){let code=fs.readFileSync('src/visualization/viewer/main.mjs','utf8');code=code.replace(/^  if\(manifest\)\{const near=nearPlaneForSceneBounds.*$/m,'');code=code.replace('const controls=new OrbitControls','window.__auditRenderer=renderer;const controls=new OrbitControls');r.respond({status:200,contentType:'text/javascript',body:code});}else r.continue();});await page.goto('http://127.0.0.1:8874/src/visualization/viewer/?manifest=/project/tower_hamlets/runs/canary_wharf_appearance_western_neighbors_001/manifest.json',{waitUntil:'networkidle0',timeout:180000});await page.waitForFunction(()=>window.urbanViewer?.widgets.length===1,{timeout:180000});await page.waitForFunction(()=>!document.querySelector('canvas').getContext('webgl2').isContextLost());
report.source=await page.evaluate(async()=>{const THREE=await import('/src/visualization/vendor/three/build/three.module.js'),{GLTFLoader}=await import('/src/visualization/vendor/three/examples/jsm/loaders/GLTFLoader.js');const w=urbanViewer.widgets[0],bytes=await(await fetch(new URL(w.layer.asset,w.context.baseURL))).arrayBuffer(),gltf=await new GLTFLoader().parseAsync(bytes,'');window.__diag={THREE,raw:gltf.scene,w,materials:new Map(),originalCamera:w.context.camera.position.toArray(),originalQuaternion:w.context.camera.quaternion.toArray()};w.context.scene.add(gltf.scene);gltf.scene.visible=false;const meshes=[];gltf.scene.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)__diag.materials.set(m,{transparent:m.transparent,opacity:m.opacity,side:m.side,depthWrite:m.depthWrite,metalness:m.metalness,roughness:m.roughness});const b=new THREE.Box3().setFromObject(o);meshes.push({name:o.name,owner:o.userData.building_id,materials:mats.map(m=>({name:m.name,transparent:m.transparent,opacity:m.opacity,depthWrite:m.depthWrite,side:m.side,metalness:m.metalness,roughness:m.roughness})),triangles:(o.geometry.index?.count||o.geometry.attributes.position.count)/3,bounds:[b.min.toArray(),b.max.toArray()]});});return{batchStats:w.batchStats,meshes,glbSha256:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('')};});
const experiments=[{name:'overview-batched',source:'batch',group:'all',variant:'original'},{name:'overview-raw',source:'raw',group:'all',variant:'original'},{name:'overview-raw-opaque',source:'raw',group:'all',variant:'opaque'}];
for(const near of [5,50,500])experiments.push({name:'overview-raw-near'+near,source:'raw',group:'all',variant:'original',near});
for(const group of ['Credit','Canada'])for(const variant of ['original','opaque','frontside','matte'])experiments.push({name:group.toLowerCase()+'-isolated-'+variant,source:'raw',group,variant});
if(process.env.UWM_SPECKLE_PHASE==='sampling'){experiments.length=0;for(const variant of ['original','opaque','matte'])experiments.push({name:'overview-'+variant,source:'raw',group:'all',variant,near:500});experiments.push({name:'overview-supersample2',source:'raw',group:'all',variant:'original',near:500,samples:2});experiments.push({name:'overview-supersample4',source:'raw',group:'all',variant:'original',near:500,samples:4});for(const group of ['Credit','Canada'])experiments.push({name:group.toLowerCase()+'-overview-isolated',source:'raw',group,variant:'original',near:500,overviewCamera:true});}
for(const e of experiments){const started=Date.now();const state=await page.evaluate(e=>{const d=__diag,{THREE,w,raw}=d;for(const [m,old] of d.materials){Object.assign(m,old);if(e.variant==='opaque'){m.transparent=false;m.opacity=1;m.depthWrite=true;}if(e.variant==='frontside')m.side=THREE.FrontSide;if(e.variant==='matte'){m.metalness=0;m.roughness=1;}m.needsUpdate=true;}
 w.group.visible=e.source==='batch';raw.visible=e.source==='raw';const selected=[];raw.traverse(o=>{if(o.isMesh){o.visible=e.group==='all'||o.name.startsWith(e.group+'_');if(o.visible)selected.push(o);}});const c=w.context.camera,look=d.look||(d.look=c.lookAt.bind(c));let position,target;
 if(e.group==='all'||e.overviewCamera){position=d.originalCamera;const q=new THREE.Quaternion(...d.originalQuaternion),forward=new THREE.Vector3(0,0,-1).applyQuaternion(q);target=new THREE.Vector3(...position).add(forward).toArray();}
 else{const box=new THREE.Box3();selected.forEach(o=>box.union(new THREE.Box3().setFromObject(o)));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=size.length()*1.35;target=center.toArray();position=center.clone().add(new THREE.Vector3(-1,.4,1).normalize().multiplyScalar(distance)).toArray();}
 __auditRenderer.setPixelRatio(e.samples||1);c.lookAt=()=>{c.position.set(...position);look(...target);};c.lookAt();c.near=e.near||.2;c.updateProjectionMatrix();c.updateMatrixWorld();urbanViewer.setTime(0);return {position,target,near:c.near,far:c.far,selectedMeshes:selected.length,renders:urbanViewer.performanceStats.renders};},e);await page.waitForFunction(n=>urbanViewer.performanceStats.renders>n,{},state.renders);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(out,e.name+'.png')});report.experiments.push({...e,...state,captureElapsedMs:Date.now()-started});}
await page.evaluate(()=>urbanViewer.dispose());}finally{await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}console.log(out);
})().catch(e=>{console.error(e);process.exit(1)});
