import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';D=R/'references'
r=json.loads((D/'quay1_lidar_review.json').read_text());n=json.loads((D/'quay1_native001.json').read_text())
r['identity']={'name':'1 West India Quay','basis':'Named Overture/OSM w309188472@5; primary developer confirms identity, architect HOK and residential/hotel use.'}
r['native_review']={'source':n['source'],'sha256':n['sha256'],'objects':len(n['objects']),'vertices':len(n['objects'][0]['vertices']),'z_min':0,'z_max':111,'mapped_parts':[],'alias_properties_present':False,'height_basis':'source_reported_height'}
r['visual_review']={'inspected':True,'images':['quay1_lidar_review.png','quay1_roof_detail001.png','pexels-ollie-craig-11491155.jpeg'],'observations':['DSM shows broad near106 and near108 m ODN roof bands and patterned elevated crown returns up to114.345 m ODN in the3m inset.','Northwest hook/recess contains low returns; east high-return outline extends outside mapped footprint. No footprint shift or invented infill adopted.','Ollie photograph contains a curved glass tower left of Credit Suisse consistent with projected owner location; crown shows thin projecting structures. This is a probable identity association, not exact camera calibration or roof-plane evidence.'],'photo_projection':'exports/quay1-photo-projection-001/projection.json','photo_limit':'Approximate z0..111 projection x274.6..386.5 y548.0..833.8 at1921x1280; existing independent camera discrepancy about119px is not a confidence interval. No raycast occlusion or precise crown dimension established.'}
r['height_interpretation']={'source_reported_architectural_m':111,'baseline_scene_top_m':111,'baseline_implied_odn_m':115.28000021,'observed_roof_band_scene_m':[106.0570068359375-4.28000021,108.0205078125-4.28000021],'developer_reported_quay_relative_feet':360,'developer_feet_converted_m':109.728,'warning':'Do not equate architectural/quayside-relative height with ODN, or replace crown by DSM-DTM median. Mapped111m applied at scene0 is an inherited assumption, not survey alignment.'}
r['temporal_applicability']={'developer_project_years':'2002–2004','actual_local_raster_capture_date':None,'assessment':'Completion precedes candidate catalogue intervals, but local flight date and present roof condition remain unresolved.'}
r['sources_text']=[{'url':'https://www.manhattanloft.co.uk/projects/no-1-west-india-quay','accessed_at':'2026-10-07','status':'text_only','kind':'text','observation':'Developer reports2002–2004,32storeys,6penthouses with private roof gardens and360ft rise above quayside.','image_acquired':False},{'url':'https://www.multiplex.global/projects/west-india-quays/','accessed_at':'2026-10-07','status':'search_result_only_then_open_denied403','kind':'text','observation':'Search result reports111m and roof gardens; full page denied. No retry or image acquisition. Do not treat as fully inspected source.'}]
r['recommendation']={'ready_for_integration':False,'replace_ids':[],'geometry_created':False,'reason':'Both flat111m baseline and simple lowered roof omit the crown hierarchy. DSM supports multiple terraces/crown returns but outer roof extent and thin upper structure remain unverified.','next_action':'Use permitted close crown/elevation evidence or an independently validated camera identification before fitting the curved crown and terraces. Original footprint and baseline remain unchanged.'}
r['verification_scope']={'native_read':True,'plots_actually_viewed':True,'photo_actually_viewed':True,'candidate_glb_check':'not_applicable_no_candidate','neighbor_mesh_check':'not_applicable_no_geometry_change'}
r['artifact_hashes']={p:hashlib.sha256((D/p).read_bytes()).hexdigest() for p in ['quay1_native001.json','quay1_lidar_review.png','quay1_roof_detail001.png','pexels-ollie-craig-11491155.jpeg']}
(D/'quay1_review001.json').write_text(json.dumps(r,indent=2)+'\n')
(D/'quay1_review001.md').write_text('''# 1 West India Quay — roof and source-height review

No replacement geometry or region modification. Native scene owner836 contains one148-vertex mesh, z0..111m, mapped OSM w309188472@5,33floors, no mapped parts or alias metadata.

The inspected raster contains broad roof returns near106.057 and108.021m ODN (scene101.777/103.741m using common4.28000021m datum), plus structured crown returns to114.345m ODN within the3m inset. Northwest low returns and eastern high returns outside the footprint prevent automatic footprint-constrained segmentation. The queue median cannot define the building's architectural top.

The developer describes the2002–2004 project,32storeys, six penthouses with roof gardens, and360feet above the quay. This approximate relative height (109.728m) is not an ODN top. The contractor search result reports111m; opening its page returned403 and was not retried. No contractor imagery acquired.

The licensed Ollie image was actually inspected. Approximate owner projection x275–386/y548–834 (1921wide) corresponds plausibly to the curved glass tower left of Credit Suisse; thin crown projections are visible. Camera uncertainty and lack of plan visibility prevent measuring the crown or reusing arbitrary facade details. This is a useful future reference lead, not a verified detailed crown reconstruction.

No native/GLB export or neighbor-change check is claimed: no candidate was made. Keep original footprint and source-height baseline while obtaining or validating specific crown evidence. Actual local LiDAR capture date remains unknown. See quay1_review001.json and exports/quay1-photo-projection-001/projection.json for sources, hashes and exact diagnostic scope.
''')
print(D/'quay1_review001.json')
