"""Record inspected evidence and bounded non-modification decision for 25 Churchill Place."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007/references'
r=json.loads((R/'e62_lidar_review.json').read_text()); n=json.loads((R/'e62_native001.json').read_text())
r['identity']={'name':'25 Churchill Place','confidence':'strong spatial/text correspondence; Overture has no name','basis':['Owner 2021 map locates 25/30 Churchill Place directly south of Churchill Place, east of Bellmouth Passage. Inspected cached map image.','GLA site description and KPF text agree on south dock/west Bellmouth Passage context; mapped 23-floor office record agrees with supplier text.'],'mapped_osm_record':'w183241873@10'}
r['native_review']={'source':n['source'],'sha256':n['sha256'],'objects':len(n['objects']),'mesh_vertices':len(n['objects'][0]['vertices']),'z_min':0,'z_max':130,'height_basis':'source_reported_height','parts_or_aliases_found':False,'geometry_changed':False}
r['visual_review']={'inspected':True,'images':['e62_lidar_review.png','e62_roof_detail001.png'],'observations':['Lower roof return near 120.974 m ODN occupies broad north/east/south bands and a western notch.','Upper area is not a single level: coherent upper patches near 128.663 m ODN connect through broad intermediate high surfaces.','Five repeated elevated patches occur along the east strip and another at the south; function and construction details are unknown.','The north low strip is spatially coherent and high western returns extend outside the mapped footprint; offset, overhang, atrium and mixed returns cannot be distinguished by these rasters alone.','No image-based facade reconstruction performed.']}
r['height_interpretation']={'existing_scene_roof_m':130,'existing_implied_odn_m':134.28000021,'lower_observed_plateau_scene_m':120.97400665283203-4.28000021,'upper_observed_plateau_scene_m':128.6630096435547-4.28000021,'warning':'Architectural height, maximum roof/crown level, DSM return and local DSM-DTM median are different quantities. Do not lower to 120.178 m queue value.','source_conflict':'GLA 2010 describes 130 m as a 2008 permission and separately describes a later reduced proposal. Supplier describes approximately 130 m and 2014 completion. Neither is an as-built ODN survey.'}
r['temporal_applicability']={'completion_year_reported':2014,'actual_local_lidar_capture_date':None,'catalogue_overlap_not_flight_date':True,'assessment':'Building completion precedes candidate catalogue survey intervals, but this does not establish the actual local flight date or current roof condition.'}
r['recommendation']={'ready_for_integration':False,'replace_ids':[],'geometry_created':False,'reason':'A single lowered extrusion would erase coherent multi-level/sloped roof structure and ignore roof/footprint disagreement. Retain current source-height baseline until bounded roof layout/outer envelope are reconciled.','next_action':'Acquire or review a permitted roof/elevation reference for this specific owner, then fit the broad roof surfaces and resolve north-edge and western-overhang correspondence without shifting the mapped footprint.'}
r['text_sources']=[{'id':'e62_heidelberg_20261007','url':'https://www.heidelbergmaterials.co.uk/en/case-study/25-churchill-place','kind':'text','status':'text_only','accessed_at':'2026-10-07','observation':'Supplier describes approximately 130 m, 23 floors, four western atria and 2014 completion.','capture_date':None,'image_acquired':False},{'id':'e62_gla_2010','url':'https://www.london.gov.uk/sites/default/files/public:/public:/PAWS/media_id_111804/25_churchill_place_report.pdf','kind':'text','status':'text_only','accessed_at':'2026-10-07','observation':'Pages 7–10 locate the site and distinguish the 2008 23-storey 130 m permission from a 2010 proposal reduced by four storeys. This is planning evidence, not an as-built measurement.','capture_date':None,'image_acquired':False},{'id':'e62_kpf_20261007','url':'https://www.kpf.com/project/25-churchill-place','kind':'text','status':'text_only','accessed_at':'2026-10-07','observation':'Architect identifies south dock and west Bellmouth Passage context, tapered mitred corners and west-facing pocket atrium.','capture_date':None,'image_acquired':False}]
r['acquisition_failures']=[{'url':'https://25churchillplace.com/downloads/25_Churchill_Place_CWG_Plans.pdf','result':'web timeout','used':False}]
r['artifact_hashes']={f:hashlib.sha256((R/f).read_bytes()).hexdigest() for f in ['e62_lidar_review.png','e62_roof_detail001.png','e62_native001.json']}
(R/'e62_review001.json').write_text(json.dumps(r,indent=2)+'\n')
(R/'e62_review001.md').write_text('''# e62 / 25 Churchill Place — evidence review

No geometry was changed and no replacement module is approved by this review.

The retained native scene has one 128-vertex mesh, z=0..130 m, using source-reported height. The underlying Overture source is OSM way w183241873@10, 23 floors, 130 m. Spatial context and primary text strongly identify 25 Churchill Place.

The inspected DSM has 3,140 footprint cells: 913 near the lower 120.974 m ODN plateau, 591 near the upper 128.663 m ODN plateau, 1,240 intermediate roof cells and 210 below 30 m ODN. These bands are descriptive and do not exhaust all returns. Under the shared datum the two plateaus are 116.694 and 124.383 m scene z. They are not a justification for replacing the whole building by either level.

The roof has distinct broad lower strips, high central/western areas and repeated eastern elevated patches. The high-return outline extends west of the mapped footprint while a north strip contains low returns. Neither rooftop equipment nor an overhang/atrium interpretation has been established. The categorized diagnostic uses 0=below30, 1=120.7..121.3, 3=128.4..128.9, and 2=all other returns; category2 is not exclusively roof.

The supplier reports approximately 130 m and 2014 completion. GLA planning history links 130 m to a 2008 permission and separately describes a reduced 2010 proposal. These are different source contexts; no final ODN crown survey has been found. Do not lower to the queue's local DSM-DTM median. Actual local raster capture vintage remains unknown.

Next: review a permitted specific roof/elevation reference, then fit broad surfaces and reconcile north and west edges. Keep original footprint, parts and aliases. No native/GLB candidate or neighbor-intersection test is claimed because no model was created. Native source identity/bounds were directly inspected; diagnostics were actually viewed. See e62_review001.json for hashes, primary URLs and details.
''')
print(R/'e62_review001.json')
