from pathlib import Path
import bpy,json,hashlib
from mathutils import Vector
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/fff_seam-comparison-001';src=R/'exports/fff_boundary-ground-contact-001/ground-contact.blend';sha=hashlib.sha256(src.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(src));before={o.name:[tuple(v.co) for v in o.data.vertices] for o in bpy.data.objects if o.type=='MESH'};d=json.load(open(O/'fff_seam-authoring.json'));me=bpy.data.meshes.new('Clipped regional illustrative ground');me.from_pydata(d['vertices'],[],d['triangles']);me.update();ob=bpy.data.objects.new('Dataset boundary — clipped original flat ground',me);bpy.context.scene.collection.objects.link(ob);ob['building_id']='diagnostic-clipped-regional-ground';ob['scope']='Local window only, patch subtracted exactly. Open step is dataset/display boundary, NOT real cliff.';m=bpy.data.materials.new('Original illustrative ground comparison');m.diffuse_color=(.53,.49,.43,1);me.materials.append(m)
s=bpy.context.scene;s.render.resolution_x=1200;s.render.resolution_y=850;s.render.resolution_percentage=100;s.cycles.samples=32;cam=s.camera;C=Vector((-501,362,1.0));cam.data.ortho_scale=36
for name,offset in [('overview',(-27,-34,20)),('seam',(-22,-25,7)),('top',(0,0,50))]:
 cam.location=C+Vector(offset);cam.rotation_euler=(C-cam.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(O/('fff_seam-'+name+'.png'));bpy.ops.render.render(write_still=True)
assert all([tuple(v.co) for v in bpy.data.objects[n].data.vertices]==v for n,v in before.items());bpy.ops.wm.save_as_mainfile(filepath=str(O/'fff_seam-comparison.blend'),compress=False);bpy.ops.object.select_all(action='DESELECT')
for o in bpy.data.objects:
 if o.type=='MESH':o.select_set(True)
expected={o.name:len(o.data.polygons) for o in bpy.data.objects if o.type=='MESH'};bpy.ops.export_scene.gltf(filepath=str(O/'fff_seam-comparison.glb'),export_format='GLB',use_selection=True,export_extras=True,export_draco_mesh_compression_enable=False);bpy.ops.wm.open_mainfile(filepath=str(O/'fff_seam-comparison.blend'));assert all([tuple(v.co) for v in bpy.data.objects[n].data.vertices]==v for n,v in before.items());bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'fff_seam-comparison.glb'));ms=[o for o in bpy.data.objects if o.type=='MESH'];assert len(ms)==len(expected);assert all(len(o.data.polygons)==expected[o.name] for o in ms);assert hashlib.sha256(src.read_bytes()).hexdigest()==sha
(O/'fff_seam-checks.json').write_text(json.dumps({'native_reopened':True,'glb_reimported':True,'mesh_count':len(ms),'terrain_and_building_vertices_exactly_unchanged':True,'source_unchanged':True,'source_sha256':sha,'old_new_plan_overlap_m2':d['old_new_plan_overlap_m2'],'display_step_range_m':d['old_minus_dtm_at_seam_range_m'],'physical_continuity':False,'boundary_label':'dataset/display boundary, not real cliff','visual_reviewed':False},indent=2))
