from pathlib import Path
import json,numpy as np,math
from scipy.optimize import least_squares
from shapely.geometry import Polygon,box,Point
from shapely.ops import transform
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';g=json.loads((R/'geometry.json').read_text());f=next(f for f in g['buildings'] if 'f0aeb767' in f['id']);p=Polygon(f['geometry'][0]['outer']);tower=next(f for f in g['buildings'] if '12b707fc' in f['id']);pt=Polygon(tower['geometry'][0]['outer']);d=np.load('cache/tower_hamlets/citi_neighbor_roof.npz');u,v,z=d['u'],d['v'],d['z'];m=d['mask'];th=math.radians(-10);co,si=math.cos(th),math.sin(th);uv=lambda x,y:(x*co+y*si,-x*si+y*co);xy=lambda u,v:(u*co-v*si,u*si+v*co);pu=transform(uv,p);high=pu.intersection(box(-10,-157,1000,-105));low=pu.difference(high);hc=m&(u>-10)&(v>-157)&(v<-105);lc=m&(u>-18)&(u<-12)&(v>-155)&(v<-107);center=np.array([u[hc].mean(),v[hc].mean()]);A=np.stack([np.ones(u.shape),u-center[0],v-center[1]],-1)
def fit(mm):return least_squares(lambda c:A[mm]@c-z[mm],[87.5,0,0],loss='soft_l1',f_scale=.25).x
c=fit(hc);level=float(np.median(z[lc]));checks={}
for label,arr in [('u',u),('v',v)]:
 folds=np.floor((arr-arr[hc].min())/4).astype(int)%3;e=[]
 for k in range(3):
  tt=hc&(folds==k);cc=fit(hc&~tt);e.extend((A[tt]@cc-z[tt]).tolist())
 checks[label]={'cells':len(e),'rmse':float(np.sqrt(np.mean(np.array(e)**2))),'median_abs':float(np.median(abs(np.array(e)))),'p90_abs':float(np.percentile(abs(np.array(e)),90))}
plane=[float(c[0]-c[1]*center[0]-c[2]*center[1]),float(c[1]),float(c[2])];dat=4.28000021
reg=[{'name':'outer_lower_roof','plane_odn_c_a_u_b_v':[level,0,0],'support_uv':[{'outer':list(q.exterior.coords),'holes':[list(h.coords) for h in q.interiors]} for q in getattr(low,'geoms',[low])]}, {'name':'main_roof','plane_odn_c_a_u_b_v':plane,'support_uv':[{'outer':list(high.exterior.coords),'holes':[list(h.coords) for h in high.interiors]}]}]
shared=p.boundary.intersection(pt.boundary);a,b=np.array(shared.coords[0]),np.array(shared.coords[-1]);L=shared.length;va,vb=uv(*a)[1],uv(*b)[1];ts=sorted([0,1]+[(vv-va)/(vb-va) for vv in [-157,-105] if 0<(vv-va)/(vb-va)<1]);segments=[]
for t0,t1 in zip(ts,ts[1:]):
 mid=a+(b-a)*(t0+t1)/2;um,vm=uv(*mid);hi=high.covers(Point(um,vm));c0=plane if hi else [level,0,0];ends=[a+(b-a)*tt for tt in [t0,t1]];zs=[c0[0]+c0[1]*uv(*q)[0]+c0[2]*uv(*q)[1]-dat for q in ends];segments.append({'t_interval':[t0,t1],'s_m_from_a':[t0*L,t1*L],'xy_endpoints':[q.tolist() for q in ends],'top_scene_z_endpoints':zs,'zone':'main_roof' if hi else 'outer_lower_roof','formula':'linear interpolation along segment; topODN=plane[0]+plane[1]*u+plane[2]*v thenminus4.28000021','plane_odn_c_a_u_b_v':c0})
report={'building_id':f['id'],'datum_odn_m':dat,'rotation_degrees':-10,'regions':reg,'main_fit_center_uv':center.tolist(),'main_fit_coefficients_centered':c.tolist(),'main_fit_holdout_all_cells':checks,'lower_support_cells':int(lc.sum()),'lower_level_odn':level,'lower_support_height_p10_p90':np.percentile(z[lc],[10,90]).tolist(),'selection':'Geometricdomains chosenafterDSM inspection; allvalid4minsetcells inselectedsupport used, testresidualsnotrejected. Mainu>-10,-157<v<-105;lowerplateausupport -18<u<-12,-155<v<-107. Fullfootprintlowdomain isdescriptive completion beyondconditionaldata support.','limitations':['Mixed2017–2020DSM vs2026footprint;lowreturncorners notroofholes.','Domainbreaks cleaned/geometricallyestimated; spatialmodelselection notindependentlyvalidated.','No facadeappearance assigned fromtowerphoto.'],'shared_citi_interface':{'citi_owner':tower['id'],'line_a':a.tolist(),'line_b':b.tolist(),'length_m':L,'segments':segments,'instruction':'Citi facade detail alongsharedline mustbegin at piecewisetop; sourcebaseline54m isobsolete for thisstudy. KeeporiginalCiti body andotherfacades.'}};(R/'references/citi_neighbor_roof_fit.json').write_text(json.dumps(report,indent=2));(R/'references/citi_neighbor_shared_interface.json').write_text(json.dumps(report['shared_citi_interface'],indent=2));print(json.dumps(report['shared_citi_interface'],indent=2));print(c,checks,level)
