from pathlib import Path
import json,hashlib,zipfile
S=Path(__file__).resolve().parent;R=S/'input/canary_wharf_20261007';O=R/'exports/hipped_residential-massing-001';r=json.loads((R/'references/hipped_residential_study.json').read_text());fit=r['fit'];context=json.loads((O/'context_mesh_check.json').read_text());audit=json.loads((R/'references/hipped_residential_roof_review.json').read_text())
rep={'scope':r['scope'],'replacement_ids':r['replacement_ids'],'datum_odn_to_scene_subtract_m':4.28000021,'actual_capture_date':None,'candidate_fit':fit,'native_original':context['original_native'],'native_mesh_count':4,'triangles':80,'scene_peak_z_m':5.792265415,'footprint_partition_checks':r['checks'],'shared_boundary_contracts':[x for x in audit['shared_boundaries'] if '5' in x['labels']],'neighbor_contacts':'12 BVH triangle pairs confined to the two touching neighbor owners 90a03f9a and 2c5e193a. Source footprints meet with no mapped overlap. Neighbors remain flat at6m. Surface BVH is not a solid-boolean penetration proof.','actual_visual_inspection':['references/hipped_residential_roof_review.png','references/hipped_residential_fit.png','exports/hipped_residential-massing-001/overview.png','exports/hipped_residential-massing-001/rear.png','exports/hipped_residential-massing-001/context-review.png'],'visual_findings':['Centralroofhascoherentfourplanesandshort ridge;no arbitrary equipment or windows.','Mappedsmalloutline steps preserved;plane extrapolation to these steps remains estimated.','Touchingneighbors still baselineflat roofs visiblyhigher than refinedeaves,reflectingunresolvedneighbors.','WesternUshapedpairneeds separate lowannex model and ridge evidence; globalhipfails withoffsetbound hits andcoherentnegativewingresiduals.','Easternpairparameters vary materially acrossfolds;withheld.'],'limitations':r['limitations'],'sources':[{'id':'ea_dsm_1m_existing','provider':'Environment Agency','license':'Open Government Licence v3.0','license_url':'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/','local_file':'references/ea_dsm_1m.tif','capture_date':None,'use':'Roof geometry hypothesis','sha256':hashlib.sha256((R/'references/ea_dsm_1m.tif').read_bytes()).hexdigest()},{'id':'overture_buildings_20260923','provider':'Overture Maps / OpenStreetMap','license':'ODbL-1.0','use':'Mapped footprint and hipped roof classification; no optical texture'}]}
(O/'report.json').write_text(json.dumps(rep,indent=2)+'\n')
(O/'report.md').write_text('''# Central hipped residential roof candidate

Owner `94620c8d-1ce4-4fe5-9991-77971c4e6b31` only. Four closed editable solids, 80 triangles. Native original flat height was 6 m; fitted ridge is scene z 5.7923 m, with lower sloped eaves. Common scene datum is ODN 4.28000021 m. Native and independent GLB checks pass. This is a descriptive roof/massing refinement, not a facade reconstruction or current survey.

All 72 valid DSM cells in the 1 m geometric inset entered the robust fit. Median absolute residual 0.039 m; RMSE 0.574 m; P95 1.920 m. Six spatial holdout folds have RMSE 0.119–0.795 m, with no search-bound hits. Robust fitting downweights larger errors; the low median is not a whole-building accuracy claim. Edge extrapolation and small footprint steps remain estimated. Actual raster capture date unresolved.

Five selected owners form one touching row. The western two owners include low-return wings and a mapped courtyard: a single whole-block hip does not fit, and all six folds hit the offset bound. The eastern paired owners have unstable eaves/slopes and spatially coherent residuals. Those four owners remain unchanged. No arbitrary cuts or equipment have been introduced.

Actual DSM diagnostics, isolated overview/rear, and native-neighbor context render were inspected. The candidate touches only its mapped east/west neighbors in the surface BVH test (12 triangle pairs). This is consistent with intended shared walls but not a general volume-intersection proof. Flat base z0, material colors, and blank facades remain illustrative. No optical roof or facade verification and no openings reconstruction.

Source archive includes authoring and diagnostic code, numerical reports, and provenance only; no source photos or DSM pixels. Environment Agency LiDAR: OGL v3. Overture/OSM footprints: ODbL-1.0. Coordinate and source hashes are in JSON reports.
''')
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in sorted(S.glob('hipped_residential_*.py')):z.write(f,'authoring/'+f.name)
 for f in sorted((R/'references').glob('hipped_residential_*.json')):z.write(f,'references/'+f.name)
 for f in ['report.md','report.json','numerical_verification.json','context_mesh_check.json']:z.write(O/f,f)
print(hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest())
