from pathlib import Path
import json,hashlib,zipfile
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';E=R/'exports/jpm25-evidence-001';O=R/'exports/jpm25-roof-study-001';d=json.load(open(O/'jpm25-checks.json'));d['visual_reviewed']=True;d['visual_review']='Final overview/rear/roof and actual DSM/profile/fit images inspected. Initial overview framing corrected before final retention.';(O/'jpm25-checks.json').write_text(json.dumps(d,indent=2))
source={'owner':'overture-building-25c810fb-17d0-4331-9c9a-6cc5f5bb8042','identity':'25 Bank Street / JP Morgan','sources':[{'kind':'text','url':'https://jpmorganchaseco.gcs-web.com/news-releases/news-release-details/jp-morgan-acquires-new-european-investment-bank-headquarters/','publication_date':'2010-12-20','accessed_at':'2026-10-07','status':'actually_read','supported_claims':['25 Bank Street acquired for 2012 headquarters','Building completed in 2003'],'geometry_derivation':'identity/epoch only; no image acquired'},{'kind':'text','url':'https://www.jpmorgan.com/disclosures/uk_entities_jul2012','status':'403 denied; stopped, no retry or alternate route'},{'kind':'vector','source_id':'overture_buildings_20260923','record':'OSM w140144145@16','update_time':'2022-08-26T06:48:43Z','attribution':'© OpenStreetMap contributors, ODbL-1.0; Overture Maps','reported_height_m':153,'height_not_scene_datum':True},{'kind':'lidar','source':'references/ea_dsm_1m.tif and ea_dtm_1m.tif','license':'Environment Agency Open Government Licence','capture_date':None,'local_vintage':'unresolved','geometry_derivation':'per existing approved project source records'},{'kind':'street_photo','source_id':'pexels_ollie_11491155','actually_inspected':True,'result':'Mainly occluded by Newfoundland; no tower/podium breakline measurement supported. Existing camera uncertainty approximately119px. No photo in package.'}]};(E/'jpm25-sources.json').write_text(json.dumps(source,indent=2))
(O/'jpm25-report.md').write_text('''# 25 Bank Street bounded massing candidate

Owner 25c810fb, 6473.251833 m²; retained baseline OMC001 is one full-footprint 153 m extrusion. Progress/history showed no previous owner refinement. Source OSM height153m is reported architectural height, not ODN elevation; 33 floors are not used to infer roof height. Official JPMorgan 2010-12-20 announcement identifies25 Bank Street and completion2003. Raster capture vintage remains unknown. Existing approved Ollie photo actually inspected: Newfoundland largely occludes target, so it does not constrain tower/podium edges. One Bank and Morgan facades are not borrowed.

Candidate preserves entire mapped footprint and all owners. Three closed editable solids: continuous low podium, northern L-shaped tower, central raised roof envelope. Roof ODN 54.507004 /154.285004 /159.720001 becomes scene50.227004 /150.005003 /155.440001 by subtracting shared4.28000021. Base zero inherited, not detected foundation. Plateau separation is supported, but tower breaklines and low-return cover are estimated. No fabricated courtyard, windows, parapet arrays or roof equipment. Small raised returns around tower perimeter are omitted, not claimed absent.

All6470 valid DSM cells are scored against actual native mesh top by BVH ray.6470hits, RMSE27.103345m, MAE11.806633m, P95abs48.357975m,3457within1m. Same-cell flat baseline RMSE88.316148m. Large remaining errors are explicit:1177cells below20ODN,987matchDTM±1cm;1089low cells lie under estimated continuous podium cover. Ground-like raster returns do not establish an open courtyard or confirmed glass dropout. Some low edge cells are covered by tower; no topology cut made to optimize them away.

Alternating5m-strip holdout of fitted heights gives full-domain RMSE27.10352/27.10299m. It does not independently validate manually chosen breaklines. Moving tower breaklines±1m changes RMSE24.367–31.131m, demonstrating edge sensitivity; smaller residual alone cannot choose physical outline. Central raised envelope is approximately39×16m in mapped-oriented axes, not an identified equipment object.

Shared owner899 edge76.091525m and5df0 edge31.827533m retain exact plan boundaries, zero positive plan overlap. Both shared tops are podium scene50.227004m; no upper tower reaches those shared edges. Neighbor899 remains on hold and untouched. Ground/transport clearances remain unresolved. Individual solids are closed and zero-area-face-free, but touching internal caps remain; no global boolean-union simulation volume claim.

Native reopening, independent GLB import, IDs/counts/bounds checks pass; actual overview/roof/rear and evidence plots inspected. Whole-footprint body remains partial estimated massing; facade/entrance details unresolved. Source archive contains only own scripts/evidence and original geometry records/hashes, no photos or large rasters. No region/progress/global files changed.
''')
files=list(P.glob('jpm25*.py'))+list(E.glob('jpm25*'))+[R/'references/jpm25-authoring001.json',O/'jpm25-report.md',O/'jpm25-checks.json']
with zipfile.ZipFile(O/'jpm25-source.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in files:
  if f.is_file():z.write(f,str(f.relative_to(P)))
(O/'jpm25-hashes.json').write_text(json.dumps({f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in O.iterdir() if f.is_file() and f.name!='jpm25-hashes.json'},indent=2));print(d)
