from pathlib import Path
import json,hashlib,zipfile
P=Path('project/tower_hamlets');R=P/'input/canary_wharf_20261007';O=R/'exports/kpmg15-massing-001';c=json.loads((O/'context_mesh_check.json').read_text());v=json.loads((O/'verification.json').read_text());v['limitations']='Five descriptive roof levels, unknown actualcapturevintage. Source68.5m isOSMreportedAGL and broadly agrees DSM-minuslocalDTM; candidate scenez usesODNminus4.28000021. SharedFitchroof interface unresolved. Internalcoincidentwalls retained; no facade reconstruction.';(O/'verification.json').write_text(json.dumps(v,indent=2));(O/'visual_review.json').write_text(json.dumps({'actual_inspected':['overview.png','context-review.png','references/kpmg15_roof_review.png','references/kpmg15_aligned.png'],'decision':'Independentcandidate HOLD sharedinterface and mixedNEdomain. Broad roof levels spatially supported; centralpatch closure does not establish functionalidentity. Wholeowner RMSEslightlyworse thanoldflat dueeastlowreturns, medabs improves.','neighbor':'Fitch6e7e remains original68.5m. Exactshared69.1586m line retained. BVHsharedwallcontacts expected; surfaceintersection test not volumeoverlap proof.','bvh_overlap_pairs':sum(a['overlap_triangle_pairs'] for a in c['pairs']),'fullmesh_errors':'references/kpmg15_mesh_comparison.json'},indent=2))
files=list(P.glob('kpmg15*.py'))+list((R/'references').glob('kpmg15*.json'))+list((R/'references').glob('kpmg15*.png'))+[P/'prepare_water8_study.py',R/'geometry.json'];(O/'source_snapshot.json').write_text(json.dumps({str(f):hashlib.sha256(f.read_bytes()).hexdigest() for f in files},indent=2))
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in files:z.write(f,str(f))
 for n in ['verification.json','context_mesh_check.json','visual_review.json','source_snapshot.json']:z.write(O/n,n)
(O/'archive_sha256.json').write_text(json.dumps({'sources.zip':hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest()},indent=2))
print('triangles',v['total_triangles'],'contacts',sum(a['overlap_triangle_pairs'] for a in c['pairs']))
