from pathlib import Path
import json,hashlib,zipfile
P=Path('project/tower_hamlets');R=P/'input/canary_wharf_20261007';O=R/'exports/kpmg-fitch-interface-review-001';O.mkdir(exist_ok=True)
r={'status':'Evidence-only HOLD; no paired replacement asset','actual_inspected':['references/kpmg_fitch_roof_review.png','references/kpmg_fitch_interface.png'],'native_source':'exports/appearance-jpm25-001/region.blend','native_evidence':'references/kpmg15_group_native.json','findings':['Bothnatives68.5mOSMreportedheight, not ML. Localgroundheight differs from4.28000021flatdatum.','177cell northernshared domain: Fitchmedian75.172ODN/KPMG75.1845ODN, difference.0125m; oneplane holdoutRMSE1.34m reveals mixedpatches, not perfectlycontinuousroof.','Southernconnected503lowcells across bothowners:353DSM=DTMwithin1cm, medianAGL~0. Cannot distinguish realopenarea and terrainfilledDSM without additional evidence.'],'decision':'Do notforcealignment, do not inferground-levelvoid, do not buildcompletepairedcandidate. KPMG001 remains independenthypothesis. No globaledits.','limitations':['Actualperbuildingrastercapturevintage unresolved.','Read-onlynativeFitch48verts/KPMG28verts, priorKPMGcontextactualviewed; nonewgeometry requiringGLBverification generated.','Exactsharedline69.1586m mapped, raster1m. SharedlineorientationpositivewestKPMG/negativeeastFitch; profilesretainallcells.']};(O/'review.json').write_text(json.dumps(r,indent=2))
files=list(P.glob('kpmg_fitch*.py'))+list((R/'references').glob('kpmg_fitch*.json'))+list((R/'references').glob('kpmg_fitch*.png'))+[R/'references/kpmg15_group_native.json'];(O/'source_snapshot.json').write_text(json.dumps({str(f):hashlib.sha256(f.read_bytes()).hexdigest() for f in files},indent=2))
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in files:z.write(f,str(f))
 z.write(O/'review.json','review.json');z.write(O/'source_snapshot.json','source_snapshot.json')
(O/'archive_sha256.json').write_text(json.dumps({'sources.zip':hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest()},indent=2))
