from pathlib import Path
import json
import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter1d
from scipy.signal import find_peaks
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
O=Path(__file__).resolve().parent/'input/canary_wharf_20261007/exports/one_canada_roof_seam005';im=np.asarray(Image.open('cache/tower_hamlets/one_canada_detail_gap003/crown-inspection.png').convert('L'),float);xs=np.arange(420,501);ys=np.arange(165,310);v=np.array([im[np.rint(y+(xs-460)*.166).astype(int),xs].mean() for y in ys]);res=v-gaussian_filter1d(v,3);peaks,_=find_peaks(-res,distance=3,prominence=.9)
r={'source':'references/pexels-altaf-shah-19330277.jpeg','inspected_crop':'cache/tower_hamlets/one_canada_detail_gap003/crown-inspection.png','annotation_coordinates_crop_px':{'triangle_left':[112,308],'apex':[394,72],'triangle_right':[1080,470],'sample_x_range':[420,500],'sample_reference_y_range':[165,309],'course_projected_slope':.166,'formula':'sample_y=round(reference_y+(x-460)*0.166)','dark_course_reference_y':(peaks+165).tolist()},'measurement':{'detected_dark_rows':len(peaks),'median_pitch_px':float(np.median(np.diff(peaks))),'mean_pitch_px':float(np.mean(np.diff(peaks))),'full_projected_altitude_px_approx':283,'adopted_divisions_estimated':68},'component_mapping':{'fine_courses':'67 shallow horizontal strips making approximately68 divisions of 25m existing rise; inferred pitch0.367647m vertical. Only westface.','major_seams':'Five representative central divisions retained from004; exact count/position still estimated.','material':'Neutral gray metallic westface estimated from Anna color photo plus Altaf grayscale morphology; no exact reflectance inference.'},'limitations':['Pixel periodicity is not metric survey; perspective and varying contrast limit exact count.','Detection marks describe readable sample only; fullface count extrapolated.','12mm outward relief,40mm verticalwidth and raisedsection inferred; image does not establish section.','No photo redistributed or used as texture; no random noise.']}
(O/'photo_component_annotations.json').write_text(json.dumps(r,indent=2));fig,axs=plt.subplots(1,2,figsize=(12,4),layout='constrained');axs[0].plot([112,394,1080,112],[308,72,470,308],c='black');axs[0].fill([420,500,500,420],[165-40*.166,165+40*.166,309+40*.166,309-40*.166],alpha=.2);axs[0].invert_yaxis();axs[0].set(aspect='equal',title='Photo coordinate diagram (no image reproduced)',xlabel='Crop x px',ylabel='Crop y px');axs[1].plot(ys,res);axs[1].scatter(ys[peaks],res[peaks],s=15,c='red');axs[1].set(title='Readable horizontal-course cadence:33 troughs',xlabel='Reference crop y px',ylabel='Detrended grayscale');fig.savefig(O/'course-cadence.png',dpi=160)
