from pathlib import Path
import json,hashlib,numpy as np
from PIL import Image,ImageDraw
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/morgan-lowerbase-evidence-001';O.mkdir(exist_ok=True);C=P.parent.parent/'cache/tower_hamlets/morgan_lowerbase_evidence001';C.mkdir(parents=True,exist_ok=True)
def proj(p,a,W,H):
 fw=np.array([np.cos(a[3])*np.cos(a[4]),np.sin(a[3])*np.cos(a[4]),np.sin(a[4])]);r=np.array([np.sin(a[3]),-np.cos(a[3]),0]);u=np.cross(r,fw);rr=r*np.cos(a[5])+u*np.sin(a[5]);uu=-r*np.sin(a[5])+u*np.cos(a[5]);q=np.asarray(p)-a[:3];return np.c_[W/2+np.exp(a[6])*(q@rr)/(q@fw),H/2-np.exp(a[6])*(q@uu)/(q@fw)]
G=json.loads((R/'geometry.json').read_text())['buildings'];b=next(b for b in G if 'b317a51d' in b['id']);edge=[b['geometry'][0]['outer'][13],b['geometry'][0]['outer'][14]];a=np.array(json.loads((R/'exports/photo-study-morgan-near-001/photo-study-near-landmark.json').read_text())['hypotheses'][0]['refitted_parameters']);lines=[];im=Image.open(R/'references/pexels-zak-h-36533700.jpeg').resize((1368,1824));d=ImageDraw.Draw(im)
for z in [0,4,8,12,16,18.85]:
 pix=proj([[*p,z] for p in edge],a,1368,1824);lines.append({'z_scene_m':z,'pixels':pix.tolist()});d.line([tuple(p) for p in pix],fill='yellow',width=2);d.text(tuple(pix[1]),str(z),fill='red')
im.crop((130,900,380,1260)).resize((500,720)).save(C/'height-diagnostic.png');Image.open(R/'references/pexels-zak-h-36533700.jpeg').crop((365,2010,760,2740)).save(C/'source-crop.png')
ollie=json.loads((R/'references/morgan_photo_camera.json').read_text());target=next(b for b in G if 'fcc7f76d' in b['id']);r=np.array(target['geometry'][0]['outer']);pr=proj(np.c_[r,np.full(len(r),156)],np.array(ollie['parameters_xyz_yaw_pitch_roll_logf']),1921,1280)
photo_reviews=[{'file':f,'sha256':hashlib.sha256((R/'references'/f).read_bytes()).hexdigest(),'actually_inspected':True,'finding':finding} for f,finding in [('pexels-ollie-craig-11491155.jpeg','No independently separable Barclays corners; projected roof envelope near HSBC/OCS group. Camera approximate.'),('pexels-anna-rynkowska-19572396.jpeg','HSBC/OCS/Citi and Cabot Place fill central skyline; no separate Barclays silhouette.'),('pexels-altaf-shah-19330277.jpeg','OCS and foreground pediment dominate; no identifiable Barclays corner.'),('pexels-zak-h-36533700.jpeg','No independent Barclays silhouette; usable near Morgan lower base visible on left.')]]
out={'owner_id':b['id'],'source_id':'pexels_zak_36533700','new_scope':'Unmodeled lower pale base on edge13, below existing upper facade starting18.85scene. Proposal only.','edge_index':13,'edge_enu':edge,'camera_reference':'exports/photo-study-morgan-near-001/photo-study-near-landmark.json','camera_quality':'Conditional seven-landmark fit; scalar RMS18.33px, individual residuals up to44px; owner discrimination stronger than dimensional calibration.','source_crop_original_pixels':[365,2010,760,2740],'actually_inspected':True,'supported_components':['Two groups of tall narrow recessed glazing with small upper transoms and pale vertical stone divisions','Two broad dark openings with shallow segmental arch heads and darker brown reveals','Pale horizontal stone bands between glazing tiers and pale central/outer piers'],'occluded_or_uncertain':['Bottom entrance geometry obscured by railings, plants, canopy and street objects; omit from initial proposal','Dark broad openings appear gridded; whether louvres/security grilles/glazing not securely resolved','Depths and absolute vertical bands remain estimates','Narrow return face right belongs to adjacent edge; exclude from edge13 proposal'],'height_projection_diagnostic':lines,'existing_upper_detail_not_modified':'morgan_south-facade-001 z18.85..28.48, already retained; no duplicate upper windows','recommended_next_step':'Align visible pale cornice and arch bands to conditional edge13 camera, preserve explicit image-pick uncertainty. Build only upper narrow-window tier and two arch panels if coordinator approves correspondence; preserve body/roof and no booleans without explicit scope.','alternate_barclays_review':photo_reviews,'ollie_barclays_roof_projection_bbox_px':[pr.min(0).tolist(),pr.max(0).tolist()],'no_geometry_authored':True};(O/'proposal.json').write_text(json.dumps(out,indent=2));print(lines);print('Barclays Ollie bbox',out['ollie_barclays_roof_projection_bbox_px'])
(O/'proposal.md').write_text('''# Morgan lower base: proposed new visible zone

Owner overture-part-b317a51d-586a-3b78-9ee5-b685a2db94a0, mapped edge13. Existing retained detail addresses only upper two-bay brown/glass facade z18.85–28.48m. The pale base beneath remains unmodeled. Actual original-resolution Zak crop inspected, showing two tall narrow-window groups/transoms and two broad shallow segmental arch heads with dark inset surfaces. Same owner/camera correspondence as prior upper bays; no neighboring facade transfer.

Propose a bounded lower-base study excluding the lowest entrances and right return face: pale piers/cornices, narrow-window tier and two curved arch reveals with dark recessed backing. Depths and vertical placement estimated; dark grid function unresolved. Do not automatically fill it with generic window arrays or claim openings surveyed. Existing body/roof/upper details unchanged. Camera uncertainty retained; height lines are diagnostic, not exact measurements.

Independent Barclays search: actual Ollie, Anna, Altaf and Zak images reviewed; none supplies a clearly separate Barclays corner/silhouette that resolves the prior hold. Ollie projection extent retained in JSON as context only. No new acquisition. Original-resolution photo crop and projection overlay are cache-only; no image packaged. Proposal only; no geometry/global changes.
''');(O/'hashes.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.iterdir() if p.is_file() and p.name!='hashes.json'},indent=2))
