from pathlib import Path
import json,hashlib,zipfile
from shapely.geometry import Polygon
from shapely.ops import unary_union
S=Path(__file__).resolve().parent;R=S/'input/canary_wharf_20261007';O=R/'exports/owner1f92-ground-contact-001';d=json.load(open(O/'input.json'));c=json.load(open(O/'checks.json'));g=json.load(open(R/'geometry.json'))
p=unary_union([Polygon(q['outer'],q.get('holes',[])) for f in g['buildings'] if any(k in f['id'] for k in ['1f9270f4','00851081']) for q in f['geometry']]);terrain=unary_union([Polygon([d['vertices'][i][:2] for i in face]) for face in d['faces']]);coverage={'footprint_area_m2':p.area,'uncovered_area_m2':p.difference(terrain).area,'patch_outside_union_3m_m2':terrain.difference(p.buffer(3)).area,'terrain_vertices':len(d['vertices']),'terrain_triangles':len(d['faces'])};assert coverage['uncovered_area_m2']<1e-8
(O/'coverage.json').write_text(json.dumps(coverage,indent=2));rows=c['checks'];count=sum(v['exterior_samples'] for v in rows);lo=min(v['exterior_residual_minmax'][0] for v in rows);hi=max(v['exterior_residual_minmax'][1] for v in rows)
(O/'report.md').write_text(f'''# Independent ground-contact candidate\n\nSelected exact retained owner1f92 scene only;0085 remains its retained9m roof. No regional edits. Existing EA1m DTM native pixel-centre triangles cover complete footprint union; uncovered area {coverage['uncovered_area_m2']:.9f}m². Patch stays inside union+3m, open surface without skirts/ramps. Datum ODN−4.28000021m.\n\nOnly zero-base lower vertices extended to DTM−0.03m display embed. All original upper coordinate locations preserved exactly. Four owner1f92 volumes remain closed.0085 inherits unjoined source face topology and is explicitly NOT certified closed; no snapping of upper coordinates was used. Coordinate-preserving duplicate welding attempted but does not resolve its inherited boundaries.\n\nExterior contact: bottom edges within0.1mm of mapped footprint boundary, subdivided to≤0.1m and11samples peredge; {count} samples, terrain projection missing0, positive residual0. Residual range {lo:.6f}..{hi:.6f}m. Internal cap diagonals separately reach+0.035979m and are not exterior floating-wall evidence. Internal faces remain estimated subsurface closure; this is not foundation geometry.\n\nActual before/after/rear renders inspected: previous1m-scale airgap disappears while roof levels remain identical. Native reopen and independent GLB triangle counts pass. Source native hash unchanged. DTM accuracy1m sampling and unknown epoch limit physical accuracy. Original regional slab/seam remains unresolved; this package is independent and cannot simply be overlaid on the old site.\n\nEvidence: checks.json,coverage.json,input.json. Source archive contains reproducible scripts, source hashes and numerical evidence; source rasters/native remain at recorded project paths.\n''')
files=[S/'owner1f92_ground_evidence.py',S/'owner1f92_ground_prepare.py',S/'owner1f92_ground_build.py',S/'owner1f92_ground_package.py',O/'input.json',O/'checks.json',O/'coverage.json',O/'report.md']
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in files:z.write(f,f.name)
h={f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in [O/'ground-contact.blend',O/'ground-contact.glb',O/'sources.zip']};(O/'hashes.json').write_text(json.dumps(h,indent=2));print(coverage,count,lo,hi,h)
