from pathlib import Path
import json,hashlib,zipfile,shutil
from shapely.geometry import Polygon,mapping
from shapely.ops import unary_union
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/owner0085-massing-001';study=json.loads((R/'references/owner0085_study.json').read_text());native=json.loads((R/'references/owner0085_native.json').read_text());ev=json.loads((O/'full_domain_evaluation.json').read_text());checks=json.loads((O/'numerical_verification.json').read_text());g=json.loads((R/'geometry.json').read_text());fs={f['id']:f for f in g['buildings']};owner=study['replacement_ids'][0];nid='overture-building-1f9270f4-be48-427a-8b63-886838c77ec9';poly=lambda f:unary_union([Polygon(p['outer'],p.get('holes',[])) for p in f['geometry']]);shared=poly(fs[owner]).boundary.intersection(poly(fs[nid]).boundary);review=json.loads((R/'references/owner0085_roof_review.json').read_text());row=review['parts'][0];c=row['center_local_xy_m'];cf=study['fit']['coefficients'];height=lambda x,y:cf[0]+cf[1]*(x-c[0])+cf[2]*(y-c[1])-4.28000021
pts=[]
for line in shared.geoms if hasattr(shared,'geoms') else [shared]:pts+=list(line.coords)
heights=[height(x,y) for x,y in pts];interface=json.loads((O/'interface_native.json').read_text());interface.update({'shared_line':mapping(shared),'shared_length_m':shared.length,'xy_footprint_overlap_m2':poly(fs[owner]).intersection(poly(fs[nid])).area,'candidate_roof_along_shared_z_range_m':[min(heights),max(heights)],'neighbor_roof_z_m':interface['neighbor_objects'][0]['max_z_m'],'contact_interval':'From z=0 to candidate shallow plane; neighbor exposed above that plane to16.074 m. All walls retained.','BVH_contact_note':'Six triangle intersections and zero nearest distance on intentional mapped shared boundary; no footprint interior overlap. Not a solid-volume Boolean proof.','neighbor_unchanged':True});(O/'interface_native.json').write_text(json.dumps(interface,indent=2))
report={'owner':owner,'status':'Frozen standalone shallow-plane roof candidate; no regional integration','source_native':{'path':native['source'],'sha256':native['source_sha256'],'unchanged':native['source_unchanged']},'meshes':len(checks['native']),'triangles':sum(a['triangles'] for a in checks['native']),'full_domain':ev['groups'],'fit':study['fit'],'shared_interface':interface,'actual_views_inspected':['overview.png','rear.png','detail.png','context-review.png','full_domain_evaluation.png','owner0085_roof_review.png','owner0085_edges.png','owner0085_edge_segments.png'],'limitations':study['limitations']+['Full-domain RMSE and P95 worsen despite core plane fit improvement; not a globally better DSM approximation.','Low edge returns are not equated with terrain or declared nonexistent architecture; no stable alternative perimeter ledge established by available1m raster.']};(O/'report.json').write_text(json.dumps(report,indent=2))
(O/'report.md').write_text(f'''# Owner0085 shallow-roof standalone candidate

Owner `{owner}`, mapped OSM w191276416@4. Original native retained owner1f92 scene selectively loaded: roof z9 m, assumed unknown height. Current candidate full mapped footprint153 m², one closed36triangle mesh; base0 retained. Source SHA{native['source_sha256']} unchanged.

Native DSM all60 cells in2m inset support ODN plane14.70688 +0.005156(x−center_x) −0.018649(y−center_y). Core RMSE0.0205 m; spatial blocked x/y holdout max0.03254 m. All80 cells in1.5m inset RMSE0.0469 m. Scene uses ODN−4.28000021 m; this is a shallow roofplane, not a new pitched roof.

Frozen native-mesh projection covers all155 valid cells, no omissions. Full-domain RMSE worsens2.646→2.897 m, P95 worsens6.080→7.441 m, medianabsolute error improves1.449→0.0219 m. All43 residuals>0.5 m lie within1.442 m of exterior. East/south profiles vary~3–15 m without a stable alternative perimeter plateau. None equal DTM within0.1 m; no claim that all lowreturns are ground, nonexistent architecture or confirmed interpolation. Roof edge limit and small ledges unresolved; no invented peripheral terraces.

Original fullfootprint retained; numerical float projected missing area9.94e−5 m²/outside2.856e−4 m², zero missing at0.1mm tolerance. Native closed manifold/nozeroarea and independent uncompressedGLB ID/triangles/bounds/material/finite checks pass. Overview/rear/detail/context and actual unfiltereddiagnostic plots inspected.

Shared mappededge with1f92 length{shared.length:.6f} m, XYoverlap0. Candidate roofalongedge z{min(heights):.6f}..{max(heights):.6f} m; untouched highneighbor roof16.074 m. Sharedwallcontact extends0..candidateplane, neighbor wall exposedabove. SixBVHtrianglecontacts are onthis mappedadjacency, not proof of volumeintersection; allwallsremain. Context showscandidate aslower adjoiningwing. Originalbase0/groundcontact, materials/facades/entrances remainunverified.

ExistingEA DSM/DTM1m OGLv3: Contains Environment Agency information © Environment Agency copyright and/or database right2022. Overture/OSM ODbL source attribution unchanged. Actual compositeflightdateunknown. No new acquisition, no regional integration/global edits. Sourcesarchive contains scripts/derivedevidence, no originalraster/photos; raster reproduction depends on existing hash-recorded projectinputs.
''')
for p in (R/'references').glob('owner0085*.png'):shutil.copy2(p,O/p.name)
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in list(P.glob('owner0085_*.py'))+list((R/'references').glob('owner0085*.json'))+list(O.glob('*.json'))+[O/'report.md']:z.write(p,str(p.relative_to(P)))
print(hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest())
