from pathlib import Path
import json,zipfile,hashlib,shutil
from shapely.geometry import Polygon
from shapely.ops import unary_union
S=Path(__file__).resolve().parent;R=S/'input/canary_wharf_20261007';O=R/'exports/owner1f92-massing-001';study=json.loads((R/'references/owner1f92_study.json').read_text());ev=json.loads((O/'full_domain_evaluation.json').read_text());verification=json.loads((O/'numerical_verification.json').read_text());native=json.loads((R/'references/owner1f92_native.json').read_text());fit=json.loads((R/'references/owner1f92_fourth.json').read_text());g=json.loads((R/'geometry.json').read_text());fs={f['id']:f for f in g['buildings']};poly=lambda f:unary_union([Polygon(p['outer'],p.get('holes',[])) for p in f['geometry']]);owner=study['replacement_ids'][0];neighbor='overture-building-00851081-a921-44b3-a74f-a20d78c92746';shared=poly(fs[owner]).boundary.intersection(poly(fs[neighbor]).boundary)
interface=json.loads((O/'interface_native.json').read_text());ni=interface['neighbor_objects'][0];intervals=[]
for ob in study['objects']:
 roof=unary_union([Polygon([ob['vertices'][k][:2] for k in face]) for face in ob['roof_faces']]);line=shared.intersection(roof.buffer(.00001))
 if line.length<.001:continue
 top=max(v[2] for v in ob['vertices']);intervals.append({'candidate':ob['name'],'shared_length_m':line.length,'candidate_interval_z_m':[0,top],'neighbor_interval_z_m':[ni['min_z_m'],ni['max_z_m']],'contact_interval_z_m':[0,min(top,ni['max_z_m'])],'candidate_exposed_above_neighbor_z_m':[ni['max_z_m'],top]})
interface.update({'mapped_shared_line_geojson':__import__('shapely.geometry',fromlist=['mapping']).mapping(shared),'shared_wall_intervals':intervals,'xy_overlap_m2':poly(fs[owner]).intersection(poly(fs[neighbor])).area,'note':'Intervals describe actual existing closed masses; no facade openings inferred and no wall removed.'});(O/'interface_native.json').write_text(json.dumps(interface,indent=2))
report={'owner':owner,'status':'Frozen standalone estimated massing; no regional integration','source_native':{'path':native['source'],'sha256':native['source_sha256'],'unchanged':native['source_unchanged']},'scope':study['scope'],'mesh_count':len(verification['native']),'triangles':sum(v['triangles'] for v in verification['native']),'full_domain':ev['groups'],'native_glb_passed':verification['passed'],'shared_wall_intervals':intervals,'shared_boundary':{'neighbor_id':neighbor,'length_m':shared.length,'xy_overlap_m2':poly(fs[owner]).intersection(poly(fs[neighbor])).area,'neighbor_unmodified':True,'candidate_shared_wall_preserved':True,'note':'Zero nearest vertex distance is intentional mapped adjacency. BVH 0 contacts does not prove gap or no coplanar contact. No wall deletion or neighbor height change.'},'actual_views_inspected':['overview.png','rear.png','detail.png','context-review.png','full_domain_evaluation.png','owner1f92_roof_review.png','owner1f92_domains.png','owner1f92_perimeter.png','owner1f92_fourth.png'],'limitations':fit['limitations']+['Fourth-tier core spatial holdout fold RMSE 2.005/0.318/0.392 m; robust heights stable 11.737–11.745 m ODN but edge mixtures remain.','Outer 2 m P95 worsens 8.671→12.911 m despite overall P95 improvement.','Spatial height holdout conditions on estimated tier domains; breakline selection is not independent out-of-sample validation.']};(O/'report.json').write_text(json.dumps(report,indent=2))
(O/'report.md').write_text(f'''# Owner 1f92 estimated stepped roof

Owner `{owner}`. Original retained Norwood scene contains one flat mesh at z=0..9.78364563 m, confirmed by selective native load and unchanged SHA-256 {native['source_sha256']}. Original height is Microsoft ML Buildings; mapped footprint OSM w191276415@6 has 4 floors (context only).

Existing EA DSM supports four levels at ODN 20.354 / 17.478 / 14.634 / 11.739 m. All geometry uses fixed scene z = ODN − 4.28000021 m. Middle tier has a west recess. Fourth north/east ledge is supported by profiles that separate its ~11.74 m plateau from local DTM ~3 m and exterior fall. Boundary shifts ±0.5 m produce full RMSE 2.939–2.957 m. Lowest-tier spatial height holdout remains noisy (RMSE 2.005/0.318/0.392 m); stable median levels do not establish exact ledge edges.

Four closed meshes, 100 triangles. Full footprint retained (float projection missing 0.000648 m² / outside 0.000108 m²; zero missing at 0.1 mm tolerance), no designed holes. Actual frozen native triangle projection covers all 608 valid DSM cells. Full RMSE 4.935→2.939 m; median absolute error 5.509→0.041 m; P95 6.768→6.498 m. Inner 2 m RMSE 0.703 m. Outer 210 cells RMSE 4.907 m, P95 worsens 8.671→12.911 m. All transition and boundary samples remain in evaluation. Transition 114 cells RMSE 3.020 m; inner transition 77 cells RMSE 1.238 m.

Shared mapped boundary with 00851081 is {shared.length:.4f} m, XY overlap zero; adjacent source building untouched. Candidate walls retained, no facade opening assumption. Actual selective neighbor load confirms scene z=0..9 m; shared candidate tier0 z=0..16.074 m, coincident wall interval0..9 m and exposed candidate wall9..16.074 m. Exact mapped shared line and intervals recorded in interface_native.json. Native and independently imported uncompressed GLB ID, triangles, materials, bounds, finite coordinates checked; native closed manifold topology. Local context has no BVH triangle intersections, but zero nearest distance at shared boundary is intentional adjacency, not evidence of a gap.

Overview, rear, detail, local context, DSM/profile and frozen mesh residual images actually inspected. Four roof levels are coherent. Hidden facades, windows, doors, roof materials and original z=0 ground contact remain unverified; no invented details. No regional integration/global record edits. Actual flight vintage unknown.

EA DSM/DTM 1 m OGL v3: Contains Environment Agency information © Environment Agency copyright and/or database right 2022. Overture/OSM/Microsoft ML provenance ODbL as existing source records. No new acquisition. Source archive contains code, owner/native evidence and derived diagnostics; no original raster or photographs. Reproduction of raster fits requires existing hash-recorded project DSM/DTM; exact authored geometry is retained in owner1f92_study.json and native/GLB assets.
''')
for p in (R/'references').glob('owner1f92*.png'):shutil.copy2(p,O/p.name)
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in list(S.glob('owner1f92_*.py'))+list((R/'references').glob('owner1f92*.json'))+list(O.glob('*.json'))+[O/'report.md']:z.write(p,str(p.relative_to(S)))
print(hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest())
