import json,zipfile,hashlib
from pathlib import Path
from shapely.geometry import Polygon
from shapely.ops import unary_union
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/state-street-roof-study-001';D=json.loads((R/'references/state_street_authoring001.json').read_text());d=json.loads((O/'review.json').read_text());parts=[unary_union([Polygon(p['outer'],p['holes']) for p in z['geometry']]) for z in D['zones']];source=unary_union([Polygon(p['outer'],p.get('holes',[])) for f in D['sources'] for p in f['geometry']]);union=unary_union(parts);d.update({'visual_reviewed':True,'visual_review_scope':'Actually inspected roof and side massing renders plus DSM spatial maps. No facade photograph verification.','source_owner_ids':[f['id'] for f in D['sources']],'object_ownership':{name:{'building_id':z['owner_id'],'source_owner_ids':z['source_owner_ids']} for name,z in zip(d['objects'],D['zones'])},'roof_fit':{'north_boundary':D['north_boundary_fit'],'zones':[{k:z[k] for k in ['owner_id','label','height_m','roof_median_odn_m','all_cell_residual']} for z in D['zones']]},'geometry_checks':{'max_partition_overlap_m2':max(a.intersection(b).area for i,a in enumerate(parts) for b in parts[i+1:]),'source_union_symmetric_difference_m2':union.symmetric_difference(source).area,'raw_boundary_hausdorff_m_including_submicrometre_partition_seams':union.boundary.hausdorff_distance(source.boundary),'external_boundary_hausdorff_after_10micrometre_seam_closure_m':union.buffer(.00001).boundary.hausdorff_distance(source.buffer(.00001).boundary)},'identity':'20 Churchill Place / State Street, confirmed mapped name and primary architect text','primary_text_source':D['identity_source'],'unverified':D['unverified'],'artifact_sha256':{n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['state-street.blend','state-street.glb']}});(O/'review.json').write_text(json.dumps(d,indent=2));ledger={'sources':[{'id':'ea_lidar_dsm_1m','license':'Open Government Licence v3','use':'Roof spatial planes,ODN minus4.28000021','capture_date':'Composite mixed2017–2020; per-cell date unknown'},{'id':'overture_buildings_20260923','license':'ODbL1.0','use':'group parent and parts footprints,source floor counts'},{'id':'adamson_20_churchill_text','url':D['identity_source'],'use':'Text-only identity/completion2009 and16storeys; no imagery derivation'}],'photos_reviewed_not_used':['Anna19572396','Zak36533700','Altaf19330277','Ollie11491155','Miguel30021866'],'no_photo_geometry_claim':True};(O/'source_ledger.json').write_text(json.dumps(ledger,indent=2))
with zipfile.ZipFile(O/'source_snapshot.zip','w',zipfile.ZIP_DEFLATED) as z:
 for name in ['source.py','review.json','source_ledger.json']:z.write(O/name,name)
 for name in ['state_street_spatial001.json','state_street_spatial001.png','state_street_authoring001.json','state_street_roof_detail001.png']:z.write(R/'references'/name,'references/'+name)
 for name in ['audit_state_street001.py','prepare_state_street001.py','check_state_street001.py','package_state_street001.py']:z.write(Path(__file__).with_name(name),name)
 for name in ['crossrail_partial_assembly.py','crossrail_diagrid_candidate.py']:z.write(R/'src/buildings'/name,'buildings/'+name)
print(d['object_count'],d['geometry_checks'])
