from pathlib import Path
import json,shutil,zipfile,hashlib
from shapely.geometry import Polygon
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';O=R/'exports/park10-massing-001';r=json.loads((R/'references/park10_study.json').read_text());g=json.loads((R/'geometry.json').read_text());fs=[f for f in g['buildings'] if f.get('parent_id')==r['parent_id']];p,q=[Polygon(f['geometry'][0]['outer']) for f in fs];r['sibling_interface']={'id':fs[0]['id'],'shared_geometry_wkt':p.boundary.intersection(q.boundary).wkt,'shared_length_m':p.boundary.intersection(q.boundary).length,'overlap_area_m2':p.intersection(q).area,'preserved_native_height_m':39};r['replacement_ids']=[r['building_id']];r['native_audit']='park10_native.json';(R/'references/park10_study.json').write_text(json.dumps(r,indent=2));
pth=O/'context_mesh_check.json';d=json.loads(pth.read_text());d['interpretation']='26BVH candidate/sibling triangle contact pairs at intended shared interface; nearest0m. Both are vertical prisms on nonoverlapping mapped partitions, with float precision rounding. This supports sharedwall contact, not a measured penetration volume. No other building pairs flagged.21rays offset5cm sample west sharededge. Parent/sibling not modified.';d['actual_visual_review']='Context review actually inspected: tower and retained39m sibling meet; no gross visual intrusion. SurfaceBVH cannot certify allsolidvolumes.';pth.write_text(json.dumps(d,indent=2));
(O/'visual_review.json').write_text(json.dumps({'actual_inspected':['overview.png','roof-after.png','context-review.png','detail.png'],'finding':'Continuous full footprint mass with central high roof band; coarse stepped shape is descriptive. Preserve sibling and no facade added.','decision':'Geometry is provisionally assemblable; current roof authenticity unverified. Unknown raster capture vintage and2020completion do not establish temporal applicability.','limitations':r['limitations']},indent=2));S=O/'source_snapshot';S.mkdir(exist_ok=True)
for f in list(P.glob('*park10*.py'))+list((R/'references').glob('park10*'))+[P/'prepare_water8_study.py',R/'geometry.json',O/'verification.json',O/'visual_review.json',O/'context_mesh_check.json',O/'context-review.png',Path('cache/tower_hamlets/park10_roof.npz')]:
 if f.is_file():shutil.copy2(f,S/f.name)
with zipfile.ZipFile(O/'sources.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in sorted(S.iterdir()):z.write(f,f.relative_to(O))
print(r['sibling_interface']);print([(q['name'],q['scene_z_m'],q['authored_constant_level_spatial3m_strip_holdout_all_test_cells']) for q in r['regions']]);print(hashlib.sha256((O/'sources.zip').read_bytes()).hexdigest())
