import json,zipfile,hashlib
from pathlib import Path
from shapely.geometry import Polygon
from shapely.ops import unary_union
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/credit999-roof-study-002';D=json.loads((R/'references/credit999_authoring002.json').read_text());d=json.loads((O/'review.json').read_text());pp=[unary_union([Polygon(q['outer'],q['holes']) for q in z['geometry']]) for z in D['zones']];p=Polygon(D['source_geometry']['geometry'][0]['outer']);d.update({'visual_reviewed':True,'visual_review_scope':'Actually inspected roof and side renders and spatial DSM fit; no facade verification','identity':D['identity'],'fit':D['spatial_fit'],'neighbors':D['neighbors'],'interface_3a':D['interface_3a'],'unverified':D['unverified'],'all_cell_residuals':{z['label']:z['all_cell_residual'] for z in D['zones']},'geometric_checks':{'symmetric_difference_m2':unary_union(pp).symmetric_difference(p).area,'zone_overlap_m2':sum(a.intersection(b).area for i,a in enumerate(pp) for b in pp[i+1:])},'artifact_sha256':{n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['credit999.blend','credit999.glb']}});(O/'review.json').write_text(json.dumps(d,indent=2));ledger={'identity_primary_text':'https://www.sandybrown.com/project/','identity_fact':'17 Columbus Courtyard mapped position; roof geometry from EA DSM only.','sources':['Overture/OSM footprint ODbL1.0','EA1m DSM OGLv3 roofgeometry'], 'photo_coverage':'Existing licensedOllie inspected but mainlyoccluded; no facade borrowed','raster_safety':'Window intersected datasetextent; 999 window clipped before reading and coordinate transform; original999audit explicitly superseded in corrections file'};(O/'source_ledger.json').write_text(json.dumps(ledger,indent=2))
with zipfile.ZipFile(O/'source_snapshot.zip','w',zipfile.ZIP_DEFLATED) as z:
 for n in ['source.py','review.json','source_ledger.json']:z.write(O/n,n)
 for n in ['credit999_authoring002.json','credit999_identity_dsm.png','credit999_roof_detail002.png','credit999_crs_check001.json','bounded_raster_window_audit001.json','credit999_audit_conclusion001.json']:z.write(R/'references'/n,'references/'+n)
 for n in ['audit_credit999001.py','prepare_credit999002.py','check_credit999002.py','package_credit999002.py','check_bounded_raster_windows001.py']:z.write(Path(__file__).with_name(n),n)
 for n in ['crossrail_partial_assembly.py','crossrail_diagrid_candidate.py']:z.write(R/'src/buildings'/n,'buildings/'+n)
print(d['all_cell_residuals'],d['geometric_checks'])
