import json,zipfile,hashlib
from pathlib import Path
from shapely.geometry import Polygon
from shapely.ops import unary_union
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/credit3a-roof-study-001';D=json.loads((R/'references/credit3a_authoring001.json').read_text());d=json.loads((O/'review.json').read_text());pp=[unary_union([Polygon(q['outer'],q['holes']) for q in z['geometry']]) for z in D['zones']];p=Polygon(D['source_geometry']['geometry'][0]['outer']);d.update({'visual_reviewed':True,'visual_review_scope':'Actually inspected roof and side renders and spatial DSM fit; no facade verification','identity':D['identity'],'fit':D['spatial_fit'],'all_cell_residuals':{z['label']:z['all_cell_residual'] for z in D['zones']},'geometric_checks':{'symmetric_difference_m2':unary_union(pp).symmetric_difference(p).area,'zone_overlap_m2':pp[0].intersection(pp[1]).area},'artifact_sha256':{n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['credit3a.blend','credit3a.glb']}});(O/'review.json').write_text(json.dumps(d,indent=2));ledger={'identity_primary_text':D['identity_primary_text'],'identity_fact':'20Columbus11storeys linksOneCabot and17Columbus; consistentmappedpositions.','sources':['Overture/OSM footprint ODbL1.0','EA1m DSM OGLv3 roofgeometry'], 'photo_coverage':'Existing licensedOllie inspected but mainlyoccluded; no facade borrowed','raster_safety':'Window intersected datasetextent; 3a crop naturallyinside; original999audit explicitly superseded in corrections file'};(O/'source_ledger.json').write_text(json.dumps(ledger,indent=2))
with zipfile.ZipFile(O/'source_snapshot.zip','w',zipfile.ZIP_DEFLATED) as z:
 for n in ['source.py','review.json','source_ledger.json']:z.write(O/n,n)
 for n in ['credit3a_authoring001.json','credit3a_identity_audit.json','credit3a_identity_dsm.png','credit3a_roof_detail001.png','credit999_crs_check001.json','bounded_raster_window_audit001.json','credit999_audit_conclusion001.json']:z.write(R/'references'/n,'references/'+n)
 for n in ['audit_credit3a001.py','prepare_credit3a001.py','check_credit3a001.py','package_credit3a001.py','check_bounded_raster_windows001.py']:z.write(Path(__file__).with_name(n),n)
 for n in ['crossrail_partial_assembly.py','crossrail_diagrid_candidate.py']:z.write(R/'src/buildings'/n,'buildings/'+n)
print(d['all_cell_residuals'],d['geometric_checks'])
