from pathlib import Path
import json,hashlib,struct,zipfile
P=Path(__file__).resolve().parent;R=P/'input/canary_wharf_20261007';A=R/'exports/def7-massing-001';B=R/'exports/def7-closed-control-001';a=json.loads((R/'references/def7_massing_study.json').read_text());b=json.loads((R/'references/def7_closed_control_study.json').read_text());baseline=json.loads((A/'report.json').read_text())['hashes'];oldhash={f:hashlib.sha256((A/f).read_bytes()).hexdigest() for f in ['def7.blend','def7.glb']};assert all(oldhash[f]==baseline[f] for f in oldhash)
blob=(B/'def7.glb').read_bytes();length=struct.unpack_from('<I',blob,12)[0];g=json.loads(blob[20:20+length]);assert all(n['extras']['building_id']==b['parent_id'] for n in g['nodes'] if 'mesh' in n);verify=json.loads((B/'verification.json').read_text());verify.update(owner_ids_verified=True,actual_renders_inspected=['overview.png','roof.png','rear.png'],materials=g['materials']);(B/'verification.json').write_text(json.dumps(verify,indent=2)+'\n')
rows=[]
for aa,bb in zip(a['zone_diagnostics'],b['zone_diagnostics']):rows.append(dict(zone=aa['zone'],open_variant={'cells':aa['all_cells'],'within1m':aa['within_1m_cells'],'rmse':aa['all_rmse_m']},closed_variant={'cells':bb['all_cells'],'within1m':bb['within_1m_cells'],'rmse':bb['all_rmse_m']}))
r=dict(scope='Independent topology comparison; neither variant is measured courtyard/roof topology.',original_candidate_preserved=True,original_candidate_hashes=oldhash,closed_control_hashes={f:hashlib.sha256((B/f).read_bytes()).hexdigest() for f in ['def7.blend','def7.glb']},same_camera_and_lighting=True,geometry_parameters_preserved=['mapped exterior boundary','ODN roofs16.73/27.96/31.82','shared datum4.28000021','base0 illustrative','neutral material','camera poses and render settings'],changed='Only remove the58.382593m2 inferred interior opening from all three layered components; re-triangulation changes face indexing.',low_patch=a['recess_hypothesis'],comparison=rows,evidence_limits=['Mapped source footprint has no inner ring: supports preserving topology as a conservative baseline, but map incompleteness cannot prove no courtyard.','54native low-return cells at3.65–4.586ODN establish a coherent anomalous patch, not a courtyard perimeter, walls or full-height opening. Glass penetration, absent roof, data filtering and epoch differences are not independently resolved.','Original open candidate adds58.38m2 opening and vertical walls down to illustrative scene0; that is a stronger unsupported topology/depth assumption than roof-level segmentation.','Closed control puts31.82ODN roof over the same patch, conflicting with54low returns; it remains a continuity completion hypothesis, not an observed roof.','Open variant excludes patch from roof-plane metric and reports it separately, so lower RMSE does not establish correct topology or justify model selection.'],recommendation='Do not integrate the open recess as established geometry. If a provisional display massing is needed, prefer the closed control because it preserves source outer/inner-ring topology and avoids invented courtyard walls; flag the58.38m2 patch as unresolved and roof continuity as estimated. For an evidence-certified model, neither candidate is sufficient: defer topology until independent licensed aerial/roof/section evidence resolves it.',verification=verify,production_modified=False)
(B/'comparison_report.json').write_text(json.dumps(r,indent=2)+'\n')
(B/'comparison_report.md').write_text('''# def7 topology comparison

**Recommendation: do not promote the open recess to established geometry.** For provisional display massing, the closed control is preferable because it preserves the original no-hole topology and avoids inventing full-height courtyard walls. It must still mark the58.38 m² roof patch as unresolved continuity completion. Neither variant establishes measured topology; an evidence-certified choice needs independent licensed roof/section evidence.

The original candidate remains byte-for-byte unchanged in `../def7-massing-001`. This independent directory contains a no-opening control with the same outer footprint, stepped roof elevations, datum, body base, material, cameras and lighting. Its native model and GLB reopen successfully; IDs and closed-component checks pass. Actual overview, roof and rear renders were inspected for both variants.

| Evidence | Open candidate | Closed control |
|---|---|---|
| Original footprint has no inner ring | Adds a new58.38 m² opening | Preserves mapped topology |
|54coherent cells at3.65–4.586 m ODN | Consistent with absence of high returns, but does not prove courtyard/walls/depth | Puts estimated31.82 m ODN roof over contradictory low returns |
| Possible transparent roof, data filtering or acquisition differences | Unresolved | Unresolved |
| Added assumptions | Opening outline and walls to illustrative scene0 | Continuous roof across anomalous patch |

Upper-plane RMSE changes from the open candidate's separately masked domain to10.440 m with all418cells in the closed control;264/418 lie within1 m. The open candidate had260/360 within1 m plus58cells reported separately,54of them low. These use different metric domains: the apparent fit improvement from cutting out low returns cannot prove a courtyard. Lower/middle roof geometry and diagnostics are unchanged.

Same-view images: `../def7-massing-001/roof.png` and `roof.png`; corresponding overview/rear pairs remain available. No glazing panels, roof lights, courtyard floor, vegetation or facade details were invented to explain the uncertain patch. No region, progress or STATUS changes were made.
''')
with zipfile.ZipFile(B/'source.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in [P/'prepare_def7_closed_control.py',P/'build_def7_closed_control.py',P/'package_def7_topology_comparison.py']:z.write(f,'scripts/'+f.name)
 for f in [R/'references/def7_closed_control_study.json',B/'comparison_report.json',B/'comparison_report.md',B/'verification.json']:z.write(f,f.name)
print(json.dumps(r['closed_control_hashes'],indent=2))
