import json,zipfile,hashlib
from pathlib import Path
from shapely.geometry import Polygon
from shapely.ops import unary_union
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/dfbe-roof-study-002';D=json.loads((R/'references/dfbe_authoring002.json').read_text());d=json.loads((O/'review.json').read_text());pp=[unary_union([Polygon(q['outer'],q['holes']) for q in z['geometry']]) for z in D['zones']];p=Polygon(D['source_geometry']['geometry'][0]['outer']);d.update({'visual_reviewed':True,'visual_review_scope':'Actually inspected roof and side renders and spatial DSM fit; no facade verification','identity':D['identity'],'fit':D['spatial_fit'],'neighbors':D['neighbors'],'source_height_basis':D['source_height_basis'],'all_cell_residuals':{z['label']:z['all_cell_residual'] for z in D['zones']},'geometric_checks':{'symmetric_difference_m2':unary_union(pp).symmetric_difference(p).area,'zone_overlap_m2':sum(a.intersection(b).area for i,a in enumerate(pp) for b in pp[i+1:])},'artifact_sha256':{n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['dfbe.blend','dfbe.glb']}});(O/'review.json').write_text(json.dumps(d,indent=2));ledger={'identity_primary_text':D['identity_primary_text'],'identity_fact':'Council2006report pp8–9 locatesCabotPlaceWest westofDLR betweenNorth/SouthColonnade; currentowner2021map agrees.','sources':['Overture/OSM footprint ODbL1.0','EA1m DSM OGLv3 roofgeometry'], 'photo_coverage':'No verified target facade geometry; no facade borrowed','raster_safety':'Window intersected datasetextent; Window clipped before read and world coordinates'};(O/'source_ledger.json').write_text(json.dumps(ledger,indent=2))
with zipfile.ZipFile(O/'source_snapshot.zip','w',zipfile.ZIP_DEFLATED) as z:
 for n in ['source.py','review.json','source_ledger.json']:z.write(O/n,n)
 for n in ['dfbe_authoring002.json','dfbe_identity_audit.json','dfbe_identity_dsm.png','dfbe_roof_detail002.png','ea_vintage_metadata_audit001.json','bounded_raster_window_audit001.json','credit999_audit_conclusion001.json']:z.write(R/'references'/n,'references/'+n)
 for n in ['audit_dfbe001.py','prepare_dfbe002.py','check_dfbe002.py','package_dfbe002.py','check_bounded_raster_windows001.py']:z.write(Path(__file__).with_name(n),n)
 for n in ['crossrail_partial_assembly.py','crossrail_diagrid_candidate.py']:z.write(R/'src/buildings'/n,'buildings/'+n)
print(d['all_cell_residuals'],d['geometric_checks'])
