exec(open('project/tower_hamlets/audit_fff0001.py').read().split('mask=')[0])
from shapely import constrained_delaunay_triangles,set_precision
z=np.asarray(Z);mask=~np.ma.getmaskarray(Z)&np.array([p.buffer(-1).contains(Point(a,b)) for a,b in zip(x.flat,y.flat)]).reshape(x.shape);fig,ax=plt.subplots(figsize=(8,9));im=ax.scatter(x[mask],y[mask],c=z[mask],vmin=24,vmax=35,s=14);fig.colorbar(im,ax=ax,label='ODN m');ax.set_aspect('equal');fig.savefig(R/'references/fff0_roof_detail001.png',dpi=150);hist,edges=np.histogram(z[mask],bins=np.arange(0,90,.2));print([(float(edges[i]),int(hist[i])) for i in np.argsort(hist)[-8:]])
from shapely.geometry import LineString
A=np.array(p.exterior.coords[5]);B=np.array(p.exterior.coords[6]);u=(B-A)/np.linalg.norm(B-A);v=np.array([-u[1],u[0]]);uu=(x-A[0])*u[0]+(y-A[1])*u[1];vv=(x-A[0])*v[0]+(y-A[1])*v[1];seed=mask&(z>25)&(z<25.6);bounds=[float(np.percentile(uu[seed],2)),float(np.percentile(uu[seed],98)),0,float(np.percentile(vv[seed],98))];bounds=[round(q*2)/2 for q in bounds];l,h,b,t=bounds;lower=p.intersection(Polygon([A+u*a+v*c for a,c in [(l,b),(h,b),(h,t),(l,t)]]));main=p.difference(lower);zones=[]
for label,poly,band in [('main roof envelope',main,(29.2,29.6)),('south central lower roof estimate',lower,(25,25.6))]:
 mm=mask&np.array([poly.contains(Point(a,b)) for a,b in zip(x.flat,y.flat)]).reshape(x.shape);ss=mm&(z>band[0])&(z<band[1]);odn=float(np.median(z[ss]));gs=[]
 for q in ([poly] if poly.geom_type=='Polygon' else poly.geoms):
  q=set_precision(q,1e-6);gs.append({'outer':list(q.exterior.coords)[:-1],'holes':[list(r.coords)[:-1] for r in q.interiors],'triangles':[list(t.exterior.coords)[:3] for t in constrained_delaunay_triangles(q).geoms]});xx,yy=q.exterior.xy;ax.plot(xx,yy,'k',lw=1)
 res=z[mm]-odn;zones.append({'label':label,'geometry':gs,'height_m':odn-4.28000021,'roof_median_odn_m':odn,'area_m2':poly.area,'stable_residual_p95_m':None,'all_cell_residual':{'count':int(mm.sum()),'mae_m':float(np.mean(abs(res))),'p95_absolute_m':float(np.percentile(abs(res),95))}})
fig.savefig(R/'references/fff0_roof_detail001.png',dpi=150);neighbors=[]
for feat in g['buildings']:
 if feat['id'] in [f['id'],'site-support']:continue
 bp=unary_union([Polygon(q['outer'],q.get('holes',[])) for q in feat['geometry']]);gap=p.distance(bp)
 if gap<35:neighbors.append({'id':feat['id'],'name':feat.get('name'),'gap_m':gap,'overlap_m2':p.intersection(bp).area,'shared_boundary_m':p.boundary.intersection(bp.boundary).length})
D={'building_id':f['id'],'identity':'12 Bank Street; owner2021estate map location dockbuilding northofBankStreet, eastofOneBankStreet; currentoperatorprimary address corroborates.','source_geometry':f,'zones':zones,'spatial_fit':{'south_lower_rectangle_local_bounds_m':bounds,'origin_enu_m':A.tolist(),'u':u.tolist(),'v':v.tolist()},'neighbors':neighbors,'identity_primary_text':'https://www.imbiba.com/news/news/2024/10/21/imbiba-to-open-65000-sq-ft-venue-in-canary-wharf','source_height_basis':'10.6656618m is Microsoft ML Buildings /properties/height estimate, not surveyed; genericheight_basis source_reported_height obscures this. OSM maps5floors.','unverified':['Historical DSM roof envelope candidate only; currentroof agreement unverified after2024announced hospitalityconversion including rooftopbar opening2025.','Composite actual survey vintage unresolved; overlappingcatalogue2017/2018 and2020 coverage is notpixeldateproof.','Higherlocalized33–34ODN returns omitted as unclassified rooftopstructures, not inventedplant or upperstoreys.','South lowerrectangle extentestimated fromspatial25.0–25.6ODN seed; no facade reconstruction.','Fullmappedoutline preserved; groundinterface flatz0estimated; shared roofdatumODNminus4.28000021.','No currentlicensedphoto facade geometry verified; do notclaim currentrooftopbar model.']};(R/'references/fff0_authoring001.json').write_text(json.dumps(D,indent=2));print(bounds,[(q['height_m'],q['all_cell_residual']) for q in zones],neighbors)
