exec(open('project/tower_hamlets/audit_207561_identity.py').read().split('mask=')[0])
from shapely import constrained_delaunay_triangles,set_precision
from shapely.geometry import LineString
mask=~np.ma.getmaskarray(Z)&np.array([p.buffer(-1).contains(Point(a,b)) for a,b in zip(x.flat,y.flat)]).reshape(x.shape);z=np.asarray(Z);c=np.array(p.centroid.coords[0]);edge=np.array(p.exterior.coords[1])-np.array(p.exterior.coords[0]);u=edge/np.linalg.norm(edge);v=np.array([-u[1],u[0]]);a=(x-c[0])*u[0]+(y-c[1])*u[1];b=(x-c[0])*v[0]+(y-c[1])*v[1];high=mask&(z>135)&(z<155);bounds=np.percentile(a[high],[1,99]);vbounds=np.percentile(b[high],[1,99]);outline=Polygon([c+u*aa+v*bb for aa,bb in [(bounds[0]-.5,vbounds[0]-.5),(bounds[1]+.5,vbounds[0]-.5),(bounds[1]+.5,vbounds[1]+.5),(bounds[0]-.5,vbounds[1]+.5)]]).intersection(p);roof=float(np.median(z[high]));zones=[]
for label,poly,h in [(1,outline,roof-4.28000021),(0,p.difference(outline),f['height_m'])]:
 geoms=[]
 for pp in ([poly] if poly.geom_type=='Polygon' else poly.geoms):
  if pp.area<.01:continue
  pp=set_precision(pp,1e-5);geoms.append({'outer':list(pp.exterior.coords)[:-1],'holes':[list(r.coords)[:-1] for r in pp.interiors],'triangles':[list(t.exterior.coords)[:3] for t in constrained_delaunay_triangles(pp).geoms]})
 zones.append({'label':label,'height_m':h,'roof_median_odn_m':roof if label else None,'area_m2':poly.area,'stable_residual_p95_m':float(np.percentile(abs(z[high]-roof),95)) if label else None,'geometry':geoms})
report={'building_id':f['id'],'identity':'One Bank Street','source_geometry':f,'zones':zones,'unverified':['Provisional two-mass hypothesis, not full architectural reconstruction.','Western low-zone height retains old ML11.836m provisionally; it is not a surveyed podium roof.','West sweeping facade/atria cannot be derived from top-down DSM; no facade geometry invented.','Tower top footprint is regularized spatial high-return envelope; boundary from1m data and mapping differ.','EA acquisition per-pixel epoch unknown; project composite mixed2017–2020, building completed around2019.'],'method':'High DSM returns135–155m ODN, axis-aligned1st/99th percentile envelope plus0.5m rastercell, clipped full source polygon. High-roof median converted ODNminus4.28000021; low area retained provisional baseline.','source_text':[{'url':'https://www.kpf.com/project/1-and-5-bank-street','facts':'27 storeys, three trading floors, sweeping western facade and atria; confirms complex massing, not shape dimensions.'},{'url':'https://offices.canarywharf.com/wp-content/uploads/2025/04/One-Bank-Street-Brochure_v7b.pdf','facts':'Location at Eden/SouthDock and BankStreetPark besidePadium;26plant levels listed, larger lower trading floors.'}]};(R/'references/one_bank_spatial001.json').write_text(json.dumps(report,indent=2));fig,ax=plt.subplots(figsize=(8,7));im=ax.scatter(x[mask],y[mask],c=z[mask]-4.28000021,s=7,vmin=0,vmax=145);fig.colorbar(im,ax=ax);xx,yy=outline.exterior.xy;ax.plot(xx,yy,'r');xx,yy=p.exterior.xy;ax.plot(xx,yy,'k');ax.set_aspect('equal');ax.set_title('One Bank Street: high-return envelope, not complete facade');fig.savefig(R/'references/one_bank_spatial001.png',dpi=150);print(roof,zones[0]['area_m2'])
