from pathlib import Path
import json,math,hashlib,numpy as np
from shapely.geometry import Polygon
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';g=json.loads((R/'geometry.json').read_text());f=next(q for q in g['buildings'] if '55529b60' in q['id']);p=Polygon(f['geometry'][0]['outer']);old=json.loads((R/'references/novotel_lidar_review.json').read_text());a=np.array(json.loads((R/'references/morgan_photo_camera.json').read_text())['parameters_xyz_yaw_pitch_roll_logf']);C=a[:3];yaw,pitch,roll=a[3:6];fw=np.array([np.cos(yaw)*np.cos(pitch),np.sin(yaw)*np.cos(pitch),np.sin(pitch)]);right=np.array([np.sin(yaw),-np.cos(yaw),0]);up=np.cross(right,fw);rr=right*np.cos(roll)+up*np.sin(roll);uu=-right*np.sin(roll)+up*np.cos(roll)
verts=np.array([[*xy,z] for xy in f['geometry'][0]['outer'] for z in [0,f['height_m'],127]]);d=verts-C;pix=np.column_stack([1921/2+np.exp(a[6])*(d@rr)/(d@fw),1280/2-np.exp(a[6])*(d@uu)/(d@fw)])
neighbors=[]
for b in g['buildings']:
 if b['id']==f['id'] or b['id']=='site-support':continue
 for part in b['geometry']:
  q=Polygon(part['outer'],part.get('holes',[]))
  if p.distance(q)<5:neighbors.append({'id':b['id'],'name':b.get('name'),'distance_m':p.distance(q),'overlap_m2':p.intersection(q).area})
report={'building_id':f['id'],'geometry_modified':False,'mapped_area_m2':p.area,'parent_id':f['parent_id'],'has_parts':f['source_properties']['has_parts'],'current_height_m':f['height_m'],'current_height_basis':f['height_basis'],'original_ML_height_m':f['detail_parameters']['previous_height']['height_m'],'source_floors':39,'neighbors_within5m':neighbors,'operator_primary':{'url':'https://press.accor.com/accorhotels-opens-flagship-skyscraper-hotel-in-canary-wharf/?lang=eng','height_m':127,'basis':'Operator opening release; street-level reference specified in accompanying 2017 press PDF','pdf_url':'https://cdn.uc.assets.prezly.com/8ad1ff77-6835-446f-aa1d-395dde3f1e83/-/inline/no/170420_ACC_Novotel-Canary-Wharf.pdf'},'prior_lidar_review':'novotel_lidar_review.json','inset2m_stats':old['stats_by_inward_buffer_m']['2'],'datum_review':{'shared_odn_offset_m':4.28000021,'previous_local_dtm_offset_m':old['ground_scalar_m_odn'],'upper_return_odn_m':122.92400360107422,'same_ODN_envelope_in_shared_scene_m':122.92400360107422-4.28000021,'existing_scene_envelope_m':f['height_m'],'decision':'Retain existing 120.745m uncertain envelope; no standalone height change from this audit. Operator127m is physical street-relative height, not ODN.'},'ollie_projection':{'source_id':'pexels_ollie_11491155','camera_reference':'morgan_photo_camera.json','image_size':[1921,1280],'projected_xy_min':pix.min(axis=0).tolist(),'projected_xy_max':pix.max(axis=0).tolist(),'all_vertices_right_of_image':bool(np.all(pix[:,0]>1921)),'limitations':'Approximate landmark-calibrated camera; tested mapped polygon at z0,120.745,127 only, not a surveyed camera.'},'actual_inspection':['novotel_lidar_review.png','pexels-ollie-craig-11491155.jpeg','pexels-miguel-gonzalez-30021866.jpeg'],'findings':['120.745m is already an earlier LiDAR upper-envelope correction, not Microsoft ML source height.','DSM alternating tall/near-ground stripes do not form credible roof-step boundaries. The 54.53m inset median is not a roof elevation.','No Novotel facade is isolated in the inspected existing photo views. Miguel photograph concerns central estate facade/bridge and is not assigned to Novotel.','Do not manufacture new roof/facade geometry from this evidence; maintain unresolved envelope and queue for independently permitted clear image.','Blocked Pexels5044520 was not retried or accessed via alternate route.'],'source_hashes':{n:hashlib.sha256((R/n).read_bytes()).hexdigest() for n in ['geometry.json','references/novotel_lidar_review.json','references/morgan_photo_camera.json']}}
(R/'references/novotel_current_audit.json').write_text(json.dumps(report,indent=2));print(json.dumps(report['ollie_projection'],indent=2));print(neighbors)
