from pathlib import Path
import json,sys,numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import least_squares
S=Path(__file__).resolve().parent;R=S/'input/canary_wharf_20261007';sys.path.insert(0,str(R))
from src.buildings.dlr_central_frame import frame_data,FEATURE_ID
source=(S/'fit_munich_roof.py').read_text().split('fold_index=')[0].replace("ID='overture-building-118734b4-49b7-4a0b-80f8-4f7b33801433'",'ID='+repr(FEATURE_ID));ns={'__file__':str(S/'fit_munich_roof.py')};exec(compile(source,str(S/'fit_munich_roof.py'),'exec'),ns)
f=ns['f'];_,_,p=frame_data(f);x,y,z=ns['x'],ns['y'],ns['z'];inside=ns['inside'];u=x*p['axis_u'][0]+y*p['axis_u'][1];v=x*p['axis_v'][0]+y*p['axis_v'][1];half=(p['v_max']-p['v_min'])/2;mid=(p['v_max']+p['v_min'])/2;arch=np.sqrt(np.maximum(0,1-((v-mid)/half)**2));sel=ns['inner']&(z>25)&(z<50);A=np.column_stack([np.ones(sel.sum()),arch[sel]]);zz=z[sel];coeff=least_squares(lambda c:A@c-zz,[25.,12.],loss='soft_l1',f_scale=.3).x;pred=coeff[0]+coeff[1]*arch;folds=np.floor((u[sel]-u[sel].min())/5).astype(int)%3;errors=[]
for k in range(3):
 mask=folds!=k;c=least_squares(lambda c:A[mask]@c-zz[mask],coeff,loss='soft_l1',f_scale=.3).x;errors.extend((zz-A@c)[~mask])
e=np.array(errors);fig,axs=plt.subplots(1,3,figsize=(16,5),layout='constrained');im=axs[0].scatter(x[inside],y[inside],c=z[inside],s=8);fig.colorbar(im,ax=axs[0],label='DSM ODN (m)');axs[0].set_aspect('equal');axs[0].set_title('Mapped central canopy');axs[1].scatter(v[inside],z[inside],s=5,c='gray');vv=np.linspace(p['v_min'],p['v_max'],100);axs[1].plot(vv,coeff[0]+coeff[1]*np.sqrt(np.maximum(0,1-((vv-mid)/half)**2)),c='red');axs[1].set(xlabel='Across canopy (m)',ylabel='ODN elevation (m)',title='Conditional symmetric arch fit');im=axs[2].scatter(u[sel],v[sel],c=(z-pred)[sel],cmap='RdBu_r',vmin=-5,vmax=5,s=8);fig.colorbar(im,ax=axs[2],label='Observed minus fit (m)');axs[2].set_title('Residual structure');fig.savefig(R/'references/dlr_canopy_height_review.png',dpi=150)
report={'building_id':FEATURE_ID,'original_parameters':p,'conditional_selection':'2m inset,25<DSM<50ODN; not whole-surface validation','cells':int(sel.sum()),'fitted_eave_odn_m':float(coeff[0]),'fitted_rise_m':float(coeff[1]),'spatial_holdout_rmse_m':float(np.sqrt(np.mean(e**2))),'spatial_holdout_p95_abs_m':float(np.percentile(abs(e),95)),'geometry_modified':False,'limitations':['Raster upper returns not independently classified roof surface.','Optical photo not georeferenced to individual roof component.','Do not equate canopy fit with rail or platform elevation.']};(R/'references/dlr_canopy_height_review.json').write_text(json.dumps(report,indent=2));print({k:v for k,v in report.items() if k!='original_parameters'})
