"""Check requested photo-supported component classes against existing asset."""
from pathlib import Path
import json,sys,hashlib
from collections import Counter
import numpy as np
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';sys.path.insert(0,str(R))
from src.buildings.dlr_central_frame import frame_data,cylinders,FEATURE_ID
f=next(a for a in json.loads((R/'geometry.json').read_text())['buildings'] if a['id']==FEATURE_ID);_,members,params=frame_data(f);v,faces=cylinders([m for m in members if m[0]!='support_column']);existing=json.loads((R/'references/dlr_support_study.json').read_text())['objects'][0];error=float(np.max(abs(np.asarray(v)-existing['vertices'])));assert error==0;assert list(map(list,faces))==existing['roof_faces']
r={'building_id':FEATURE_ID,'source_photo':'references/dlr-geograph-5620872.jpg','photo_inspected':True,'photo_observations':['Red repeated arch trusses with paired curved longitudinal chords visible overhead.','Red diagonal members form triangular web within transverse arches.','Members run longitudinally between arches; exact counts and profiles cannot be measured from this single platform view.','Grey square-clad supportcolumns visible; their placements/dimensions are not fully recoverable.'],'existing_member_counts':dict(Counter(m[0] for m in members)),'current_asset_exact_comparison':{'max_vertex_error_m':error,'faces_identical':True},'existing_assumed_parameters':{'eave_m':params['eave'],'rise_m':params['rise'],'truss_depth_m':params['estimated_truss_depth_m'],'frame_station_count':params['frame_station_count']},'decision':'No structural geometry addition justified for requested pairedchords/webs/longitudinalmembers because all already represented exactly in existing authored supportasset. Do not create duplicate003 or claim new faithful reconstruction.','limitations':['Photo supports component categories, not estimated count,spacing,circularsections or assumed12m eave/6m rise.','Regional source must retain transparentglazing to expose existing frame; visibility is a separate rendering concern.','No platform,rail,signal or equipment reconstruction authorized or inferred.'],'geometry_modified':False,'hashes':{n:hashlib.sha256((R/n).read_bytes()).hexdigest() for n in ['references/dlr-geograph-5620872.jpg','references/dlr_support_study.json','src/buildings/dlr_central_frame.py']}}
(R/'references/dlr_structural_coverage_review.json').write_text(json.dumps(r,indent=2)+'\n');print(r['decision'])
