import json
from pathlib import Path
import numpy as np
from PIL import Image
p=Path('project/tower_hamlets/input/canary_wharf_20261007/exports/facade-speckle-diagnostic-001')
a=json.load(open(p/'report.json'));b=json.load(open(p/'supplement.json'));g=json.load(open(p/'shared_faces.json'))
rows=[]
for base,other in [('norwood-default-depth','norwood-near5'),('norwood-default-depth','norwood-near5-far1000'),('norwood-default-depth','norwood-frontside'),('norwood-default-depth','norwood-supersample2'),('credit-default-depth','credit-near5-far1000'),('credit-default-depth','credit-supersample2')]:
 x=np.array(Image.open(p/(base+'.png')).convert('RGB'))[100:900,300:1400].astype(float);y=np.array(Image.open(p/(other+'.png')).convert('RGB'))[100:900,300:1400].astype(float);d=abs(x-y);rows.append({'base':base,'comparison':other,'crop_xyxy':[300,100,1400,900],'changed_pixels':int(np.any(d>0,axis=2).sum()),'pixels_difference_over_10':int(np.any(d>10,axis=2).sum()),'mean_absolute_channel_difference':float(d.mean())})
s={'source_sha256':a['source']['glbSha256'],'errors':a['errors']+b['errors'],'experiments':a['experiments']+b['experiments'],'pixel_comparisons':rows,'geometry':g,'actual_images_reviewed':True,'limitations':['Controlled closeups use independently parsed exact GLB, isolated objects and original materials; not production batching.','Only Norwood coplanar geometry audited; no claim of all-region absence of duplicates.','Distant facade temporal shimmer not measured by still screenshots.'],'conclusion':'Depth-range change does not materially eliminate the observed fine seams. Norwood contains ten opposite-facing internal shared-wall pairs, no same-facing coplanar duplicates at 10 micrometre tolerance. Front-side-only rendering does not remove seams; 2x sampling smooths their raster appearance. Evidence supports shared-edge rasterization/partition seams rather than broad external duplicate surfaces or depth-range as dominant cause. Credit fine facade stripes are smoother at 2x sampling; distant speckling remains consistent with undersampling but is not conclusively attributed across all buildings.'}
(p/'summary.json').write_text(json.dumps(s,indent=2));print(json.dumps(rows,indent=2))
(p/'summary.md').write_text('''# Read-only facade seam diagnostic\n\nExact retained Norwood GLB SHA-256: `'''+s['source_sha256']+'''`. No model or production viewer edits. Eight controlled captures were inspected. Browser errors: none.\n\nNorwood: tightening near/far from 0.135/135060 m to 5/1000 m does not visibly eliminate fine vertical partition seams. Front-side-only materials also leave the fine seams. Double sampling smooths them. Exact GLB triangle inspection finds 40 opposite-facing triangle overlaps across ten internal shared-wall interfaces, and zero same-facing coplanar overlaps at 0.00001 m plane tolerance. This is consistent with independently closed adjoining volumes producing subpixel shared-edge raster seams; it is not evidence of broad duplicated exterior sheets. The retained full-footprint checks remain relevant; this test does not establish a visible physical hole.\n\nCredit facade: the closeup resolves regular modeled frame/window stripes. Changing clip planes gives no material visual improvement; double sampling smooths thin edges. This supports undersampling as a contributor to distant speckling, but does not conclusively classify every building or temporal shimmer. Credit geometry was not exhaustively overlap-tested.\n\nNo near/far production adjustment or architecture deletion is justified by these results. A future bounded display experiment could test antialiasing/downsampling on the actual wide camera; any shared-wall cleanup would need footprint, roof, facade and closedness regression checks.\n\nSee `summary.json` for compact camera and pixel comparisons, `shared_faces.json` for exact overlap pairs, original PNGs for screenshots. Raw `report.json`/`supplement.json` retain the larger mesh inventory. Isolated tests use raw GLB, not production batches.\n''')
