from pathlib import Path
import bpy,json,hashlib
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/seven-westferry-photo-study-001';r=json.loads((R/'references/seven_westferry_photo_study.json').read_text());bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'seven_westferry.glb'));obs=[o for o in bpy.data.objects if o.type=='MESH'];assert len(obs)==len(r['objects']);checks=[]
for q in r['objects']:
 ob=next(o for o in obs if o.name==q['name']);assert ob.get('building_id')==q['building_id'];assert ob.get('aggregate_alias_id','')==q.get('aggregate_alias_id','');v=[tuple(ob.matrix_world@v.co) for v in ob.data.vertices];expected=[[min(a[i] for a in q['vertices']) for i in range(3)],[max(a[i] for a in q['vertices']) for i in range(3)]];actual=[[min(a[i] for a in v) for i in range(3)],[max(a[i] for a in v) for i in range(3)]];err=max(abs(a-b) for row,rr in zip(expected,actual) for a,b in zip(row,rr));assert err<1e-3;assert len(ob.data.materials)>0;checks.append({'name':ob.name,'id_verified':True,'bounds_error_m':err,'material_names':[m.name for m in ob.data.materials],'triangles':len(ob.data.polygons)})
p=O/'verification.json';d=json.loads(p.read_text());d['independent_id_material_bounds_checks']=checks;d['sha256']={n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['seven_westferry.blend','seven_westferry.glb']};d['limitations']='Separate adjoining massing meshes with internal coincidentwalls, not boolean-union solids; Actual recessedSW windows; namednorthernwing hidden andplain. Massing is descriptive estimate; geometry checks do not validate inferred roofs. Nonselecteddomains unchangedbaseline.';p.write_text(json.dumps(d,indent=2)+'\n');print('Verified',len(checks),'meshes')

import struct
raw=(O/'seven_westferry.glb').read_bytes();n=struct.unpack_from('<I',raw,12)[0];gltf=json.loads(raw[20:20+n]);glass=next(m for m in gltf['materials'] if m['name']=='SevenWestferry estimated glass');assert glass['pbrMetallicRoughness']['baseColorFactor'][3]==1;assert abs(glass['extensions']['KHR_materials_transmission']['transmissionFactor']-.15)<1e-6
d=json.loads(p.read_text());d['glb_glass_material_parameters']=glass;d['glass_depth_clearance_m']={'upper_glass_to_backwall':.05,'upper_frame_to_glass':.04,'attic_glass_to_backwall':.045};d['total_triangles']=sum(q['triangles'] for q in checks);p.write_text(json.dumps(d,indent=2))
