from pathlib import Path
import bpy,json,hashlib
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/west_pyramid-massing-001';r=json.loads((R/'references/west_pyramid_study.json').read_text());bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'west_pyramid.glb'));obs=[o for o in bpy.data.objects if o.type=='MESH'];assert len(obs)==len(r['objects']);checks=[]
for q in r['objects']:
 ob=next(o for o in obs if o.name==q['name']);assert ob.get('building_id')==q['building_id'];assert ob.get('aggregate_alias_id','')==q.get('aggregate_alias_id','');v=[tuple(ob.matrix_world@v.co) for v in ob.data.vertices];expected=[[min(a[i] for a in q['vertices']) for i in range(3)],[max(a[i] for a in q['vertices']) for i in range(3)]];actual=[[min(a[i] for a in v) for i in range(3)],[max(a[i] for a in v) for i in range(3)]];err=max(abs(a-b) for row,rr in zip(expected,actual) for a,b in zip(row,rr));assert err<1e-3;assert len(ob.data.materials)>0;checks.append({'name':ob.name,'id_verified':True,'bounds_error_m':err,'material_names':[m.name for m in ob.data.materials],'triangles':len(ob.data.polygons)})
p=O/'verification.json';d=json.loads(p.read_text());d['independent_id_material_bounds_checks']=checks;d['sha256']={n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['west_pyramid.blend','west_pyramid.glb']};d['limitations']='Separate adjoining massing meshes with internal coincidentwalls, not boolean-union solids; no facade openings orposts modeled. Massing is descriptive estimate; geometry checks do not validate inferred roofs. Nonselecteddomains unchangedbaseline.';p.write_text(json.dumps(d,indent=2)+'\n');print('Verified',len(checks),'meshes')
import bmesh
checksclosed=[]
for ob in obs:
 bm=bmesh.new();bm.from_mesh(ob.data);bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=.0001);bad=sum(not e.is_manifold for e in bm.edges);zero=sum(f.calc_area()<1e-10 for f in bm.faces);assert bad==0 and zero==0;checksclosed.append({'name':ob.name,'nonmanifold_edges':bad,'weld_tolerance_for_GLTF_normal_seams_m':.0001,'zero_area_faces':zero});bm.free()
d=json.loads(p.read_text());d['independent_glb_closed_mesh_checks']=checksclosed;d['total_triangles']=sum(q['triangles'] for q in checks);d['limitations']='Descriptive roof massing, slopes/terraces estimated from DSM whose capture vintage is unresolved. Separateadjoiningclosedmeshes retaininternalwalls. Edge/cornerlowreturns unresolved. No facade reconstruction. Micrometre polygon precision cleanup.';p.write_text(json.dumps(d,indent=2))
