exec(open('project/tower_hamlets/assemble_quay1_recess_scene.py').read().split('prior=')[0].split("ID=")[0].replace("O.mkdir(exist_ok=False);",""))
# Source already opened by inherited header. Compare every unchanged UV and alias too.
ID='overture-building-a6a8ac29-204a-43a7-b4d0-af0fa65a47dc';replace=[ID,'Quay1 visible upper glass'];prior={o.name:fingerprint(o) for o in bpy.data.objects if o.type=='MESH' and o.name not in replace}
def uv(o):return [[list(v.uv) for v in layer.data] for layer in o.data.uv_layers]
source_uv={o.name:uv(o) for o in bpy.data.objects if o.type=='MESH' and o.name not in replace}
bpy.ops.wm.open_mainfile(filepath=str(O/'region.blend'));assert all(fingerprint(bpy.data.objects[n])==v and uv(bpy.data.objects[n])==source_uv[n] for n,v in prior.items())
def metadata(o,imported=False):
 o.data.calc_loop_triangles();vv=[o.matrix_world@v.co for v in o.data.vertices];return {'triangles':len(o.data.loop_triangles),'owner':o.get('building_id'),'aliases':plain(o.get('source_owner_ids',[])),'aggregate_alias_id':plain(o.get('aggregate_alias_id')),'bounds':[[min(v[i] for v in vv) for i in range(3)],[max(v[i] for v in vv) for i in range(3)]],'used_materials':sorted(set(o.data.materials[p.material_index].name for p in o.data.polygons))}
expected={o.get('research_object_id',o.name):metadata(o) for o in bpy.data.objects if o.type=='MESH'};bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'region.glb'));actual={o.get('research_object_id',o.name):metadata(o) for o in bpy.data.objects if o.type=='MESH'};assert actual.keys()==expected.keys();fail=[];maxerr=0
for k,v in expected.items():
 a=actual[k];err=max(abs(x-y) for q,r in zip(v['bounds'],a['bounds']) for x,y in zip(q,r));maxerr=max(maxerr,err)
 for field in ['triangles','owner','aliases','aggregate_alias_id','used_materials']:
  if a[field]!=v[field]:fail.append({'id':k,'field':field,'expected':v[field],'actual':a[field]})
assert maxerr<.001
(O/'roundtrip-differences.json').write_text(json.dumps(fail,indent=2));assert not fail,fail[:3]
bounds=[[min(v['bounds'][0][i] for v in expected.values()) for i in range(3)],[max(v['bounds'][1][i] for v in expected.values()) for i in range(3)]]
report={'native_reopened':True,'independent_glb_verified':True,'source_blends':{'../../runs/canary_wharf_appearance_ownerd42_001/region.blend':sourcehash,'exports/facade-detail-pilot-001/quay1-detail.blend':hashlib.file_digest(asset.open('rb'),'sha256').hexdigest()},'source_owner_ids':[ID],'bounds_enu_m':bounds,'mesh_count':len(expected),'triangles':sum(v['triangles'] for v in expected.values()),'unrelated_exact_geometry_properties_materials_and_uv':len(prior),'max_perobject_bounds_error_m':maxerr,'native_sha256':hashlib.file_digest((O/'region.blend').open('rb'),'sha256').hexdigest(),'glb_sha256':hashlib.file_digest((O/'region.glb').open('rb'),'sha256').hexdigest(),'source_sha256':sourcehash,'source_unchanged':sourcehash==hashlib.file_digest(src.open('rb'),'sha256').hexdigest(),'asset_sha256':hashlib.file_digest(asset.open('rb'),'sha256').hexdigest(),'per_object':expected,'limitations':['Original initial check compared unused material slots which GLB omits; corrected comparison checks used material identity per object.','Only two original meshes replaced plus two returns; frames and all other original objects exact.']};(O/'per-object-verification.json').write_text(json.dumps(report.pop('per_object'),indent=2));(O/'verification.json').write_text(json.dumps(report,indent=2));(O/'checks.json').write_text(json.dumps({k:v for k,v in report.items() if k!='per_object'},indent=2));print('VERIFIED',len(expected),maxerr)
