from pathlib import Path
import bpy,json,hashlib
from mathutils import Vector
R=Path(__file__).resolve().parent/'input/canary_wharf_20261007';O=R/'exports/newfoundland-study-002';r=json.loads((R/'references/newfoundland_study_002.json').read_text());ex=json.loads((O/'expected.json').read_text());bpy.ops.wm.open_mainfile(filepath=str(O/'newfoundland.blend'));obs=[o for o in bpy.data.objects if o.type=='MESH'];assert len(obs)==5
# Full-frame overview/rear correction after actual crop inspection.
s=bpy.context.scene;s.camera.data.ortho_scale=320;bpy.ops.wm.save_as_mainfile(filepath=str(O/'newfoundland.blend'),compress=False);s.render.filepath=str(O/'overview.png');bpy.ops.render.render(write_still=True)
p=r['footprint'][0]['outer'];target=Vector((sum(v[0] for v in p)/len(p),sum(v[1] for v in p)/len(p),110));s.camera.location=target+Vector((160,230,100));s.camera.rotation_euler=(target-s.camera.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(O/'rear.png');bpy.ops.render.render(write_still=True)
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(O/'newfoundland.glb'));checks=[]
for ob in [o for o in bpy.data.objects if o.type=='MESH']:
 assert ob['building_id']==r['building_id'];assert len(ob.data.polygons)==ex[ob.name]['triangles'];vs=[tuple(ob.matrix_world@v.co) for v in ob.data.vertices];bounds=[[min(v[i] for v in vs) for i in range(3)],[max(v[i] for v in vs) for i in range(3)]];err=max(abs(a-b) for rr,t in zip(bounds,ex[ob.name]['bounds']) for a,b in zip(rr,t));assert err<1e-3;assert ob.data.materials[0].name==ex[ob.name]['material'];checks.append({'name':ob.name,'triangles':len(ob.data.polygons),'bounds_error_m':err,'id_verified':True,'material':ob.data.materials[0].name})
(O/'verification.json').write_text(json.dumps({'native_reopened':True,'glb_checks':checks,'scope':r['scope'],'limitations':['Separate overlapping beams do not have detailed joint hardware or a boolean-union guarantee.','Footprint glass inset uses0.25m radial vertex offsets as estimated recess, not surveyed facade plane offsets.','All beam vertices clipped to0..220m; angle-based end shape estimated.'],'sha256':{n:hashlib.sha256((O/n).read_bytes()).hexdigest() for n in ['newfoundland.blend','newfoundland.glb']}},indent=2)+'\n')
r['objects']=[{'name':a['name'],'building_id':r['building_id'],'kind':a['name'].split('_')[-1],'vertices':[list(ob.matrix_world@v.co) for ob in [bpy.data.objects[a['name']]] for v in ob.data.vertices]} for a in checks];(R/'references/newfoundland_study_002.json').write_text(json.dumps(r,indent=2)+'\n');print('Verified',len(checks))
