(async()=>{
const fs=require('node:fs'),assert=require('node:assert/strict');const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const out='project/tower_hamlets/reports/city_activity025';fs.mkdirSync(out,{recursive:true});const b=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{const p=await b.newPage();await p.setViewport({width:1280,height:900});const errors=[],failures=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failures.push([r.status(),r.url()]);});
await p.goto('http://127.0.0.1:8878/src/visualization/legacy/viewer/3d/?scene=tower_hamlets&lite=0&pose=campus&shot=uavs&hold=1&play=0&t=300',{waitUntil:'domcontentloaded',timeout:180000});
await p.waitForFunction(()=>window.viewer?.uavs&&viewer.traffic&&document.querySelector('#loading').classList.contains('hide'),{timeout:180000});
const report=await p.evaluate(()=>{const u=viewer.uavs,T=viewer.traffic;u.playing=T.playing=false;u.update(60);const a=u.uavs.map(x=>[x.x,x.y,x.z]);u.update(80);const b=u.uavs.map(x=>[x.x,x.y,x.z]);u.update(60);T.update(300);const colors=[];viewer.model.traverse(o=>{if(o.isMesh&&o.renderOrder===-1)colors.push(o.material.color.getHexString());});return{groundColors:colors,uavCount:u.uavs.length,activeInstances:u.actors.uavs.activeCount,stations:u.flightData.stations.length,routes:u.flightData.routes.length,allHubRoutes:u.flightData.routes.every(r=>r.from_station==='S1'||r.to_station==='S1'),moved:JSON.stringify(a)!==JSON.stringify(b),seekReproducible:JSON.stringify(a)===JSON.stringify(u.uavs.map(x=>[x.x,x.y,x.z])),carCountAt300:T.count,peak:T.manifest.vehicles_peak,scene:viewer.SCENE.id};});
assert.ok(report.groundColors.length>=2&&report.groundColors.every(c=>c==='737a77'));assert.equal(report.uavCount,60);assert.equal(report.activeInstances,60);assert.equal(report.stations,6);assert.equal(report.routes,10);assert.ok(report.allHubRoutes&&report.moved&&report.seekReproducible);assert.equal(report.peak,1055);assert.ok(report.carCountAt300>500);
await p.evaluate(()=>{document.querySelector('[data-shot="uavs"]').click();viewer.uavs.playing=viewer.traffic.playing=false;viewer.traffic.t=400;viewer.traffic.update(400);const s=document.querySelector('#step');s.value=120;s.dispatchEvent(new Event('input',{bubbles:true}));});
const controls=await p.evaluate(()=>{const u=viewer.uavs;const before={uavTime:u.t,trafficTime:viewer.traffic.t,routesVisible:u.corridors.visible};document.querySelector('#l-uavs').click();const hidden=!u.markers.visible&&!u.corridors.visible&&!u.actors.uavs.group.visible;document.querySelector('#l-uavs').click();return{...before,hidden,shown:u.markers.visible&&u.corridors.visible};});assert.equal(controls.uavTime,120);assert.equal(controls.trafficTime,400);assert.ok(controls.routesVisible&&controls.hidden&&controls.shown);
await new Promise(r=>setTimeout(r,2800));await p.screenshot({path:out+'/uav-routes.png'});
await p.evaluate(()=>{document.querySelector('[data-shot="trafficMap"]').click();viewer.uavs.playing=viewer.traffic.playing=false;window.uavBeforeTrafficSeek=viewer.uavs.t;const s=document.querySelector('#step');s.value=300;s.dispatchEvent(new Event('input',{bubbles:true}));});
const traffic=await p.evaluate(()=>({count:viewer.traffic.count,t:viewer.traffic.t,stats:document.querySelector('#traffic-stats').textContent,uavTime:viewer.uavs.t,uavBeforeSeek:window.uavBeforeTrafficSeek}));assert.equal(traffic.t,300);assert.equal(traffic.uavTime,traffic.uavBeforeSeek);assert.ok(traffic.stats.includes(String(traffic.count)));await new Promise(r=>setTimeout(r,2800));await p.screenshot({path:out+'/dense-traffic.png'});
await p.evaluate(()=>document.querySelector('[data-field="wind"]').click());await p.waitForFunction(()=>!viewer.uavs.group.visible);report.uavsHiddenInPhysics=true;
assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);Object.assign(report,{passed:true,controls,traffic,errors,failures});fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
