(async()=>{
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {default:p}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');const out=process.env.UWM_BROWSER_OUTPUT||'cache/framework/camera-depth';fs.mkdirSync(out,{recursive:true});const browser=await p.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage();await page.setViewport({width:1440,height:1000});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.UWM_VIEWER_URL||'http://127.0.0.1:8874/src/visualization/viewer/?manifest=/project/tower_hamlets/runs/canary_wharf_appearance_western_neighbors_001/manifest.json',{waitUntil:'networkidle0',timeout:180000});await page.waitForFunction(()=>window.urbanViewer?.widgets.length===1,{timeout:180000});await page.waitForFunction(()=>!document.querySelector('#viewport>canvas').getContext('webgl2').isContextLost());
const state=()=>page.evaluate(()=>{const c=urbanViewer.widgets[0].context.camera,b=urbanViewer.manifest.spatial.bounds_m;return {position:c.position.toArray(),near:c.near,far:c.far,floor:Math.max(Math.max(1,...b.max.map((x,i)=>x-b.min[i]))/10000,.001),renders:urbanViewer.performanceStats.renders};});
await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const initial=await state();assert.ok(initial.near>initial.floor*10);await page.screenshot({path:path.join(out,'initial-adaptive-near.png')});
await page.mouse.move(850,500);const zoom=[];for(let i=0;i<4;i++){const before=await state();await page.mouse.wheel({deltaY:-700});await page.waitForFunction(n=>urbanViewer.performanceStats.renders>n,{},before.renders);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));zoom.push(await state());if(zoom.at(-1).near===initial.floor)break;}
assert.ok(zoom.at(-1).near<initial.near,'Real wheel dolly must lower near plane');assert.ok(zoom.every(s=>s.far===initial.far),'Far plane stays unchanged');
// Place camera inside the declared region beside a facade; only test camera changes.
await page.evaluate(()=>{const c=urbanViewer.widgets[0].context.camera,look=c.lookAt.bind(c);c.lookAt=()=>{c.position.set(-508,34,-57);look(-486,29,-66);};c.lookAt();c.updateMatrixWorld();urbanViewer.setTime(0);});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const close=await state();assert.equal(close.near,initial.floor,'Inside bounds must retain original near floor');await page.screenshot({path:path.join(out,'closeup-original-near-floor.png')});assert.deepEqual(errors,[]);await page.evaluate(()=>urbanViewer.dispose());const report={passed:true,initial,zoom,close,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
