import {setDataBase,npy,getFrame} from '../npy.js';
setDataBase('../../scenes/actuator_lab/');
const $=id=>document.getElementById(id),palette=[[40,59,135],[20,137,156],[117,199,176],[243,223,144],[237,119,75]];
const configs={};let playing=false,epoch=0,request=0;
async function config(name){return configs[name]??=await(await fetch('../../scenes/actuator_lab/'+name+'/result.json')).json();}
function render(id,data,c){const can=$(id),ctx=can.getContext('2d'),[nz,ny,nx]=c.shape_zyx,r=document.createElement('canvas');r.width=nx;r.height=ny;const rc=r.getContext('2d'),im=rc.createImageData(nx,ny);
 for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const t=Math.max(0,Math.min(4,data[y*nx+x]/10*4)),j=Math.min(3,Math.floor(t)),f=t-j;im.data.set([...palette[j].map((v,k)=>v+(palette[j+1][k]-v)*f),255],((ny-1-y)*nx+x)*4);}
 rc.putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(r,0,0,can.width,can.height);ctx.strokeStyle='#9cf9fc';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(can.width*.25,can.height*.375);ctx.lineTo(can.width*.25,can.height*.625);ctx.stroke();ctx.fillStyle='#fff';ctx.font='14px system-ui';ctx.fillText('来流 →',14,23);ctx.fillText('x = 32 m',can.width*.25+8,can.height*.35);}
function profile(a,ca,b,cb){const can=$('profile'),ctx=can.getContext('2d'),W=can.width,H=can.height,L=45,R=W-20,T=12,B=H-35;ctx.clearRect(0,0,W,H);ctx.font='12px system-ui';ctx.strokeStyle='#4b6578';ctx.fillStyle='#b1c4d4';for(let u=0;u<=10;u+=2){const y=B-u/10*(B-T);ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(R,y);ctx.stroke();ctx.fillText(u,15,y+4);}for(let x=0;x<=128;x+=32)ctx.fillText(x+' m',L+x/128*(R-L)-12,H-10);
 for(const [data,c,color] of [[a,ca,'#71c8ed'],[b,cb,'#f8a66a']]){const [nz,ny,nx]=c.shape_zyx;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<nx;x++){const y=(data[(ny/2)*nx+x]+data[(ny/2-1)*nx+x])/2;const X=L+(x+.5)/nx*(R-L),Y=B-y/10*(B-T);x?ctx.lineTo(X,Y):ctx.moveTo(X,Y);}ctx.stroke();}}
async function show(){const token=++request,index=+$('time').value,name=$('grid').value;try{const [a,b]=await Promise.all([config('control_0p5m'),config(name)]);const [ad,bd]=await Promise.all([getFrame(a.file,index),getFrame(b.file,index)]);if(token!==request)return;render('control',ad,a);render('disk',bd,b);profile(ad,a,bd,b);const m=b.metrics[index];$('clock').textContent=`${index+1} / ${b.times.length} 帧 · 模型时间 ${b.times[index].toFixed(1)} s`;$('stats').textContent=`盘区平均速度 ${m.disk_velocity.toFixed(2)} m/s · 轴向推力 ${(m.thrust_N/1000).toFixed(2)} kN · 网格 ${b.cell_m} m`;$('status').textContent=`实际计算 ${b.steps} 步 · dt ${b.dt} · GPU 峰值 ${b.metrics.at(-1).gpu_peak_gib.toFixed(2)} GiB · 尚未验证稳态或工程精度`;}catch(e){$('status').textContent='加载失败：'+e.message;stop();}}
function stop(){playing=false;epoch++;$('play').textContent='播放';}
async function tick(e){if(!playing||e!==epoch)return;$('time').value=(+$('time').value+1)%41;await show();if(playing&&e===epoch)setTimeout(()=>tick(e),120);}
$('play').onclick=()=>{if(playing)stop();else{playing=true;$('play').textContent='暂停';tick(++epoch);}};$('time').oninput=()=>{stop();show();};$('grid').onchange=()=>{stop();show();};show();
